"""Add new models: Literature, Email, RAGChunk, Compound, HTS, LabNotebook

Revision ID: 7043fccf47ed
Revises: d2d66c54e753
Create Date: 2025-12-06 20:36:21.394833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7043fccf47ed'
down_revision = 'd2d66c54e753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.String(length=200), nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('inchi_key', sa.String(length=50), nullable=True),
    sa.Column('canonical_smiles', sa.Text(), nullable=True),
    sa.Column('molecular_formula', sa.String(length=100), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('logp', sa.Float(), nullable=True),
    sa.Column('hbd_count', sa.Integer(), nullable=True),
    sa.Column('hba_count', sa.Integer(), nullable=True),
    sa.Column('rotatable_bonds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compounds_compound_id'), 'compounds', ['compound_id'], unique=True)
    op.create_index(op.f('ix_compounds_inchi_key'), 'compounds', ['inchi_key'], unique=True)
    op.create_index(op.f('ix_compounds_notion_page_id'), 'compounds', ['notion_page_id'], unique=True)
    op.create_index(op.f('ix_compounds_smiles'), 'compounds', ['smiles'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('from_sender', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('semantic_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_status', sa.String(length=50), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_notion_page_id'), 'emails', ['notion_page_id'], unique=True)
    op.create_index(op.f('ix_emails_title'), 'emails', ['title'], unique=False)
    op.create_table('feature_pathway_map',
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('pathway_id', sa.UUID(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True)
    )
    op.create_index(op.f('ix_feature_pathway_map_feature_id'), 'feature_pathway_map', ['feature_id'], unique=False)
    op.create_index(op.f('ix_feature_pathway_map_pathway_id'), 'feature_pathway_map', ['pathway_id'], unique=False)
    op.create_table('gene_protein_map',
    sa.Column('gene_symbol', sa.String(), nullable=False),
    sa.Column('uniprot_id', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True)
    )
    op.create_index(op.f('ix_gene_protein_map_gene_symbol'), 'gene_protein_map', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_gene_protein_map_uniprot_id'), 'gene_protein_map', ['uniprot_id'], unique=False)
    op.create_table('lab_notebook_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('entry_metadata', sa.JSON(), nullable=True),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_notebook_entries_created_at'), 'lab_notebook_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_notebook_entries_notion_page_id'), 'lab_notebook_entries', ['notion_page_id'], unique=True)
    op.create_table('literature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('zotero_item_key', sa.String(length=50), nullable=True),
    sa.Column('zotero_item_type', sa.String(length=100), nullable=True),
    sa.Column('embedding_status', sa.String(length=50), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('semantic_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_literature_doi'), 'literature', ['doi'], unique=False)
    op.create_index(op.f('ix_literature_notion_page_id'), 'literature', ['notion_page_id'], unique=True)
    op.create_index(op.f('ix_literature_title'), 'literature', ['title'], unique=False)
    op.create_index(op.f('ix_literature_zotero_item_key'), 'literature', ['zotero_item_key'], unique=True)
    op.create_table('biochemical_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.String(length=200), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('assay_name', sa.String(length=500), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('ic50', sa.Float(), nullable=True),
    sa.Column('ec50', sa.Float(), nullable=True),
    sa.Column('ki', sa.Float(), nullable=True),
    sa.Column('kd', sa.Float(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biochemical_results_compound_id'), 'biochemical_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_biochemical_results_notion_page_id'), 'biochemical_results', ['notion_page_id'], unique=True)
    op.create_index(op.f('ix_biochemical_results_result_id'), 'biochemical_results', ['result_id'], unique=True)
    op.create_table('compound_program',
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('compound_id', 'program_id')
    )
    op.create_table('hts_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.String(length=200), nullable=False),
    sa.Column('campaign_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assay_type', sa.String(length=200), nullable=True),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('library_id', sa.String(length=200), nullable=True),
    sa.Column('total_wells', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.Column('library_compound_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['library_compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hts_campaigns_campaign_id'), 'hts_campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_hts_campaigns_notion_page_id'), 'hts_campaigns', ['notion_page_id'], unique=True)
    op.create_table('lab_notebook_entry_assoc',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['lab_notebook_entries.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'entity_type', 'entity_id')
    )
    op.create_table('rag_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.String(length=500), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=500), nullable=True),
    sa.Column('zotero_item_key', sa.String(length=50), nullable=True),
    sa.Column('note_key', sa.String(length=50), nullable=True),
    sa.Column('attachment_key', sa.String(length=50), nullable=True),
    sa.Column('note_hash', sa.String(length=32), nullable=True),
    sa.Column('attachment_hash', sa.String(length=32), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=36), nullable=True),
    sa.Column('literature_id', sa.UUID(), nullable=True),
    sa.Column('email_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chunks_chunk_id'), 'rag_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_rag_chunks_email_id'), 'rag_chunks', ['email_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_literature_id'), 'rag_chunks', ['literature_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_notion_page_id'), 'rag_chunks', ['notion_page_id'], unique=True)
    op.create_index(op.f('ix_rag_chunks_source_id'), 'rag_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_zotero_item_key'), 'rag_chunks', ['zotero_item_key'], unique=False)
    op.create_table('biochemical_result_program',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['biochemical_results.id'], ),
    sa.PrimaryKeyConstraint('result_id', 'program_id')
    )
    op.create_table('hts_campaign_program',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['hts_campaigns.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'program_id')
    )
    op.create_table('hts_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.String(length=200), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('well_position', sa.String(length=50), nullable=True),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('normalized_value', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('hit_flag', sa.Boolean(), nullable=True),
    sa.Column('hit_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['hts_campaigns.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hts_results_campaign_id'), 'hts_results', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_hts_results_compound_id'), 'hts_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_hts_results_result_id'), 'hts_results', ['result_id'], unique=True)
    op.add_column('datasets', sa.Column('ingestion_status', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'ingestion_status')
    op.drop_index(op.f('ix_hts_results_result_id'), table_name='hts_results')
    op.drop_index(op.f('ix_hts_results_compound_id'), table_name='hts_results')
    op.drop_index(op.f('ix_hts_results_campaign_id'), table_name='hts_results')
    op.drop_table('hts_results')
    op.drop_table('hts_campaign_program')
    op.drop_table('biochemical_result_program')
    op.drop_index(op.f('ix_rag_chunks_zotero_item_key'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_source_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_notion_page_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_literature_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_email_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_chunk_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_table('lab_notebook_entry_assoc')
    op.drop_index(op.f('ix_hts_campaigns_notion_page_id'), table_name='hts_campaigns')
    op.drop_index(op.f('ix_hts_campaigns_campaign_id'), table_name='hts_campaigns')
    op.drop_table('hts_campaigns')
    op.drop_table('compound_program')
    op.drop_index(op.f('ix_biochemical_results_result_id'), table_name='biochemical_results')
    op.drop_index(op.f('ix_biochemical_results_notion_page_id'), table_name='biochemical_results')
    op.drop_index(op.f('ix_biochemical_results_compound_id'), table_name='biochemical_results')
    op.drop_table('biochemical_results')
    op.drop_index(op.f('ix_literature_zotero_item_key'), table_name='literature')
    op.drop_index(op.f('ix_literature_title'), table_name='literature')
    op.drop_index(op.f('ix_literature_notion_page_id'), table_name='literature')
    op.drop_index(op.f('ix_literature_doi'), table_name='literature')
    op.drop_table('literature')
    op.drop_index(op.f('ix_lab_notebook_entries_notion_page_id'), table_name='lab_notebook_entries')
    op.drop_index(op.f('ix_lab_notebook_entries_created_at'), table_name='lab_notebook_entries')
    op.drop_table('lab_notebook_entries')
    op.drop_index(op.f('ix_gene_protein_map_uniprot_id'), table_name='gene_protein_map')
    op.drop_index(op.f('ix_gene_protein_map_gene_symbol'), table_name='gene_protein_map')
    op.drop_table('gene_protein_map')
    op.drop_index(op.f('ix_feature_pathway_map_pathway_id'), table_name='feature_pathway_map')
    op.drop_index(op.f('ix_feature_pathway_map_feature_id'), table_name='feature_pathway_map')
    op.drop_table('feature_pathway_map')
    op.drop_index(op.f('ix_emails_title'), table_name='emails')
    op.drop_index(op.f('ix_emails_notion_page_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_compounds_smiles'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_notion_page_id'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_inchi_key'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_compound_id'), table_name='compounds')
    op.drop_table('compounds')
    # ### end Alembic commands ###

