"""add_model_monitoring_logs

Revision ID: a1b2c3d4e5f8
Revises: z6u7v8w9x0y1
Create Date: 2025-12-27 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f8'
down_revision = 'z6u7v8w9x0y1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_monitoring_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('ground_truth', sa.Float(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('feature_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_monitoring_logs_created_at'), 'model_monitoring_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_input_hash'), 'model_monitoring_logs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_model_id'), 'model_monitoring_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_model_version'), 'model_monitoring_logs', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_prediction_id'), 'model_monitoring_logs', ['prediction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_monitoring_logs_prediction_id'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_model_version'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_model_id'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_input_hash'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_created_at'), table_name='model_monitoring_logs')
    op.drop_table('model_monitoring_logs')
    # ### end Alembic commands ###
