"""Add signature metadata fields to Signature model

Revision ID: d2d66c54e753
Revises: 0c9c72e35979
Create Date: 2025-12-04 18:14:00.349679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2d66c54e753'
down_revision = '0c9c72e35979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signatures', sa.Column('short_id', sa.String(length=100), nullable=True))
    op.add_column('signatures', sa.Column('biomarker_role', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('signatures', sa.Column('phenotype_axes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('signatures', sa.Column('data_ownership', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_signatures_short_id'), 'signatures', ['short_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_short_id'), table_name='signatures')
    op.drop_column('signatures', 'data_ownership')
    op.drop_column('signatures', 'phenotype_axes')
    op.drop_column('signatures', 'biomarker_role')
    op.drop_column('signatures', 'short_id')
    # ### end Alembic commands ###

