"""add backup_records table for backup tracking

Revision ID: 03475894f451
Revises: 7b9ea73469db
Create Date: 2025-12-30 04:24:50.717595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03475894f451'
down_revision = '7b9ea73469db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('backup_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_records_backup_type'), 'backup_records', ['backup_type'], unique=False)
    op.create_index(op.f('ix_backup_records_checksum_sha256'), 'backup_records', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_backup_records_completed_at'), 'backup_records', ['completed_at'], unique=False)
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_records_started_at'), 'backup_records', ['started_at'], unique=False)
    op.create_index(op.f('ix_backup_records_status'), 'backup_records', ['status'], unique=False)
    op.create_index('ix_backup_records_status_created', 'backup_records', ['status', 'created_at'], unique=False)
    op.create_index('ix_backup_records_type_status', 'backup_records', ['backup_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backup_records_type_status', table_name='backup_records')
    op.drop_index('ix_backup_records_status_created', table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_status'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_started_at'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_completed_at'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_checksum_sha256'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_backup_type'), table_name='backup_records')
    op.drop_table('backup_records')
    # ### end Alembic commands ###

