"""add project_exports table

Revision ID: 054c475bc908
Revises: 592078d85ee3
Create Date: 2025-12-31 04:04:43.641305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054c475bc908'
down_revision = '592078d85ee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('entities_summary', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_exports_created_at'), 'project_exports', ['created_at'], unique=False)
    op.create_index('ix_project_exports_expires_at', 'project_exports', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_exports_expires_at', table_name='project_exports')
    op.drop_index(op.f('ix_project_exports_created_at'), table_name='project_exports')
    op.drop_table('project_exports')
    # ### end Alembic commands ###

