"""add hts plate imaging schema

Revision ID: 0e1ddc8868e5
Revises: 03475894f451
Create Date: 2025-12-30 08:04:24.606495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1ddc8868e5'
down_revision = '03475894f451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hts_plates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=False),
    sa.Column('plate_format', sa.String(length=50), nullable=False),
    sa.Column('layout_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['hts_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hts_plates_barcode'), 'hts_plates', ['barcode'], unique=True)
    op.create_index(op.f('ix_hts_plates_campaign_id'), 'hts_plates', ['campaign_id'], unique=False)
    op.create_table('hts_wells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('treatment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['plate_id'], ['hts_plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hts_wells_compound_id'), 'hts_wells', ['compound_id'], unique=False)
    op.create_index(op.f('ix_hts_wells_plate_id'), 'hts_wells', ['plate_id'], unique=False)
    op.add_column('hts_results', sa.Column('well_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hts_results_well_id'), 'hts_results', ['well_id'], unique=False)
    op.create_foreign_key(None, 'hts_results', 'hts_wells', ['well_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hts_results', type_='foreignkey')
    op.drop_index(op.f('ix_hts_results_well_id'), table_name='hts_results')
    op.drop_column('hts_results', 'well_id')
    op.drop_index(op.f('ix_hts_wells_plate_id'), table_name='hts_wells')
    op.drop_index(op.f('ix_hts_wells_compound_id'), table_name='hts_wells')
    op.drop_table('hts_wells')
    op.drop_index(op.f('ix_hts_plates_campaign_id'), table_name='hts_plates')
    op.drop_index(op.f('ix_hts_plates_barcode'), table_name='hts_plates')
    op.drop_table('hts_plates')
    # ### end Alembic commands ###

