"""extend_literature_for_papers

Revision ID: 182e90b77cc3
Revises: 98894b17e636
Create Date: 2025-12-28 16:22:20.977281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '182e90b77cc3'
down_revision = '98894b17e636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('literature', sa.Column('source', sa.String(length=50), nullable=False, server_default='zotero'))
    op.add_column('literature', sa.Column('pmid', sa.String(length=20), nullable=True))
    op.add_column('literature', sa.Column('pmc_id', sa.String(length=20), nullable=True))
    op.add_column('literature', sa.Column('mesh_terms', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('literature', sa.Column('full_text_available', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_literature_pmid'), 'literature', ['pmid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_literature_pmid'), table_name='literature')
    op.drop_column('literature', 'full_text_available')
    op.drop_column('literature', 'mesh_terms')
    op.drop_column('literature', 'pmc_id')
    op.drop_column('literature', 'pmid')
    op.drop_column('literature', 'source')
    # ### end Alembic commands ###

