"""add id_mappings table

Revision ID: 2cd9335a6a68
Revises: 905db1b1ee79
Create Date: 2025-12-31 12:43:51.485548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd9335a6a68'
down_revision = '905db1b1ee79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=200), nullable=False),
    sa.Column('organism', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'organism', name='uq_id_mapping_source_target')
    )
    op.create_index('ix_id_mappings_lookup', 'id_mappings', ['source_type', 'source_id', 'target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_id_mappings_lookup', table_name='id_mappings')
    op.drop_table('id_mappings')
    # ### end Alembic commands ###

