"""add_image_qc_records_table

Revision ID: 3297b2deeb08
Revises: 8877d15d1426
Create Date: 2026-01-01 14:06:31.160195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3297b2deeb08'
down_revision = '8877d15d1426'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_notifications', sa.Column('recipient_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_repository_notifications_recipient_id'), 'repository_notifications', ['recipient_id'], unique=False)
    op.create_foreign_key(None, 'repository_notifications', 'users', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repository_notifications', type_='foreignkey')
    op.drop_index(op.f('ix_repository_notifications_recipient_id'), table_name='repository_notifications')
    op.drop_column('repository_notifications', 'recipient_id')
    # ### end Alembic commands ###

