"""add_lifecycle_status_to_entities

Revision ID: 484be4b50b07
Revises: 3297b2deeb08
Create Date: 2026-01-01 16:00:42.806230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484be4b50b07'
down_revision = '3297b2deeb08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add lifecycle_status column to datasets
    op.add_column('datasets', sa.Column('lifecycle_status', sa.String(length=20), nullable=False, server_default='active'))
    op.create_index(op.f('ix_datasets_lifecycle_status'), 'datasets', ['lifecycle_status'], unique=False)
    
    # Migrate existing is_archived data for datasets
    op.execute("UPDATE datasets SET lifecycle_status = 'archived' WHERE is_archived = true")
    
    # Add lifecycle_status column to experiments
    op.add_column('experiments', sa.Column('lifecycle_status', sa.String(length=20), nullable=False, server_default='active'))
    op.create_index(op.f('ix_experiments_lifecycle_status'), 'experiments', ['lifecycle_status'], unique=False)
    
    # Migrate existing is_archived data for experiments
    op.execute("UPDATE experiments SET lifecycle_status = 'archived' WHERE is_archived = true")
    
    # Add lifecycle_status column to compounds
    op.add_column('compounds', sa.Column('lifecycle_status', sa.String(length=20), nullable=False, server_default='active'))
    op.create_index(op.f('ix_compounds_lifecycle_status'), 'compounds', ['lifecycle_status'], unique=False)
    
    # Add lifecycle_status column to signatures
    op.add_column('signatures', sa.Column('lifecycle_status', sa.String(length=20), nullable=False, server_default='active'))
    op.create_index(op.f('ix_signatures_lifecycle_status'), 'signatures', ['lifecycle_status'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_lifecycle_status'), table_name='signatures')
    op.drop_column('signatures', 'lifecycle_status')
    op.drop_index(op.f('ix_experiments_lifecycle_status'), table_name='experiments')
    op.drop_column('experiments', 'lifecycle_status')
    op.drop_index(op.f('ix_datasets_lifecycle_status'), table_name='datasets')
    op.drop_column('datasets', 'lifecycle_status')
    op.drop_index(op.f('ix_compounds_lifecycle_status'), table_name='compounds')
    op.drop_column('compounds', 'lifecycle_status')
    # ### end Alembic commands ###

