"""add retention_exempt column

Revision ID: 4e048f1d38fe
Revises: cacf74eae4ab
Create Date: 2026-01-02 07:00:35.578617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e048f1d38fe'
down_revision = 'cacf74eae4ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

