"""feat(imaging): add metadata models and schema updates

- Add 7 new tables: microscopes, objectives, light_sources, filter_sets, channel_configs, acquisition_settings, image_file_sets
- ALTER microscopy_images: ADD objective_id, acquisition_settings_id FKs
- ALTER microscopy_images: DROP NOT NULL constraint on well_id (P0 fix)
- ADD ome_metadata JSON column to microscopy_images (P2 fix)
- Add indexes for efficient queries on metadata tables

Revision ID: 592078d85ee3
Revises: 6ea210024846
Create Date: 2025-12-30 14:30:01.724750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592078d85ee3'
down_revision = '6ea210024846'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

