"""add retention_exempt column

Revision ID: 6327e1a98d8a
Revises: cacf74eae4ab
Create Date: 2026-01-02 07:58:54.738546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6327e1a98d8a'
down_revision = 'cacf74eae4ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first, then set default and make non-nullable
    op.add_column('compounds', sa.Column('retention_exempt', sa.Boolean(), nullable=True))
    op.add_column('datasets', sa.Column('retention_exempt', sa.Boolean(), nullable=True))
    op.add_column('experiments', sa.Column('retention_exempt', sa.Boolean(), nullable=True))
    op.add_column('signatures', sa.Column('retention_exempt', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE compounds SET retention_exempt = FALSE WHERE retention_exempt IS NULL")
    op.execute("UPDATE datasets SET retention_exempt = FALSE WHERE retention_exempt IS NULL")
    op.execute("UPDATE experiments SET retention_exempt = FALSE WHERE retention_exempt IS NULL")
    op.execute("UPDATE signatures SET retention_exempt = FALSE WHERE retention_exempt IS NULL")
    
    # Make columns non-nullable
    op.alter_column('compounds', 'retention_exempt', nullable=False)
    op.alter_column('datasets', 'retention_exempt', nullable=False)
    op.alter_column('experiments', 'retention_exempt', nullable=False)
    op.alter_column('signatures', 'retention_exempt', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signatures', 'retention_exempt')
    op.drop_column('experiments', 'retention_exempt')
    op.drop_column('datasets', 'retention_exempt')
    op.drop_column('compounds', 'retention_exempt')
    # ### end Alembic commands ###

