"""add active learning tables

Revision ID: 65947a84ef25
Revises: a7a1b2e2e8de
Create Date: 2026-01-02 17:16:00.087935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65947a84ef25'
down_revision = 'a7a1b2e2e8de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_learning_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('selection_strategy', sa.String(length=50), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('metrics_before', sa.JSON(), nullable=True),
    sa.Column('metrics_after', sa.JSON(), nullable=True),
    sa.Column('items_selected', sa.Integer(), nullable=True),
    sa.Column('items_labeled', sa.Integer(), nullable=True),
    sa.Column('items_skipped', sa.Integer(), nullable=True),
    sa.Column('new_model_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['new_model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'cycle_number', name='uq_al_cycle_model_number')
    )
    op.create_index('ix_al_cycles_model_status', 'active_learning_cycles', ['model_id', 'status'], unique=False)
    op.create_table('label_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('applicability_distance', sa.Float(), nullable=True),
    sa.Column('selection_strategy', sa.String(length=50), nullable=True),
    sa.Column('selection_batch', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.Float(), nullable=True),
    sa.Column('label_source', sa.String(length=100), nullable=True),
    sa.Column('label_confidence', sa.String(length=20), nullable=True),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labeled_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['labeled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compound_id', 'model_id', 'selection_batch', name='uq_label_queue_compound_model_batch')
    )
    op.create_index('ix_label_queue_priority', 'label_queue', ['priority_score'], unique=False)
    op.create_index('ix_label_queue_status_model', 'label_queue', ['status', 'model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_label_queue_status_model', table_name='label_queue')
    op.drop_index('ix_label_queue_priority', table_name='label_queue')
    op.drop_table('label_queue')
    op.drop_index('ix_al_cycles_model_status', table_name='active_learning_cycles')
    op.drop_table('active_learning_cycles')
    # ### end Alembic commands ###

