"""add citation tracking and semantic scholar fields

Revision ID: 68c84053ba9a
Revises: 182e90b77cc3
Create Date: 2025-12-29 04:47:30.560775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c84053ba9a'
down_revision = '182e90b77cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citing_paper_id', sa.UUID(), nullable=False),
    sa.Column('cited_paper_id', sa.UUID(), nullable=True),
    sa.Column('cited_doi', sa.String(length=500), nullable=True),
    sa.Column('cited_title', sa.String(length=1000), nullable=True),
    sa.Column('citation_context', sa.Text(), nullable=True),
    sa.Column('is_influential', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['literature.id'], ),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['literature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_citations_cited_paper_id'), 'paper_citations', ['cited_paper_id'], unique=False)
    op.create_index(op.f('ix_paper_citations_citing_paper_id'), 'paper_citations', ['citing_paper_id'], unique=False)
    op.add_column('literature', sa.Column('semantic_scholar_id', sa.String(length=50), nullable=True))
    op.add_column('literature', sa.Column('openalex_id', sa.String(length=50), nullable=True))
    op.add_column('literature', sa.Column('tldr_summary', sa.Text(), nullable=True))
    op.add_column('literature', sa.Column('citation_count', sa.Integer(), nullable=True))
    op.add_column('literature', sa.Column('influential_citation_count', sa.Integer(), nullable=True))
    op.add_column('literature', sa.Column('open_access_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_literature_openalex_id'), 'literature', ['openalex_id'], unique=False)
    op.create_index(op.f('ix_literature_semantic_scholar_id'), 'literature', ['semantic_scholar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_literature_semantic_scholar_id'), table_name='literature')
    op.drop_index(op.f('ix_literature_openalex_id'), table_name='literature')
    op.drop_column('literature', 'open_access_status')
    op.drop_column('literature', 'influential_citation_count')
    op.drop_column('literature', 'citation_count')
    op.drop_column('literature', 'tldr_summary')
    op.drop_column('literature', 'openalex_id')
    op.drop_column('literature', 'semantic_scholar_id')
    op.drop_index(op.f('ix_paper_citations_citing_paper_id'), table_name='paper_citations')
    op.drop_index(op.f('ix_paper_citations_cited_paper_id'), table_name='paper_citations')
    op.drop_table('paper_citations')
    # ### end Alembic commands ###

