"""add VCF fields to GeneticVariant

Revision ID: 6b8390d65453
Revises: 484be4b50b07
Create Date: 2026-01-01 18:29:58.991785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8390d65453'
down_revision = '484be4b50b07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genetic_variants', sa.Column('chromosome', sa.String(length=50), nullable=True))
    op.add_column('genetic_variants', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('genetic_variants', sa.Column('reference_allele', sa.String(length=500), nullable=True))
    op.add_column('genetic_variants', sa.Column('alternate_allele', sa.String(length=500), nullable=True))
    op.add_column('genetic_variants', sa.Column('quality', sa.Float(), nullable=True))
    op.add_column('genetic_variants', sa.Column('vcf_filter', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_genetic_variants_chromosome'), 'genetic_variants', ['chromosome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genetic_variants_chromosome'), table_name='genetic_variants')
    op.drop_column('genetic_variants', 'vcf_filter')
    op.drop_column('genetic_variants', 'quality')
    op.drop_column('genetic_variants', 'alternate_allele')
    op.drop_column('genetic_variants', 'reference_allele')
    op.drop_column('genetic_variants', 'position')
    op.drop_column('genetic_variants', 'chromosome')
    # ### end Alembic commands ###

