"""add biophysical assay tables (SPR, MST, DSC)

Revision ID: 6ea210024846
Revises: a455cf9a1bef
Create Date: 2025-12-30 13:02:10.622649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ea210024846'
down_revision = 'a455cf9a1bef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsc_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_name', sa.String(length=200), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('protein_concentration', sa.Float(), nullable=True),
    sa.Column('ligand_concentration', sa.Float(), nullable=True),
    sa.Column('buffer_composition', sa.String(length=500), nullable=True),
    sa.Column('scan_rate', sa.Float(), nullable=True),
    sa.Column('start_temperature', sa.Float(), nullable=True),
    sa.Column('end_temperature', sa.Float(), nullable=True),
    sa.Column('response_units', sa.String(length=50), nullable=False),
    sa.Column('concentration_units', sa.String(length=20), nullable=False),
    sa.Column('tm_value', sa.Float(), nullable=True),
    sa.Column('tm_error', sa.Float(), nullable=True),
    sa.Column('delta_h', sa.Float(), nullable=True),
    sa.Column('delta_h_error', sa.Float(), nullable=True),
    sa.Column('delta_cp', sa.Float(), nullable=True),
    sa.Column('cooperativity', sa.Float(), nullable=True),
    sa.Column('kd_thermal', sa.Float(), nullable=True),
    sa.Column('delta_tm', sa.Float(), nullable=True),
    sa.Column('baseline_quality', sa.Float(), nullable=True),
    sa.Column('peak_symmetry', sa.Float(), nullable=True),
    sa.Column('signal_to_noise', sa.Float(), nullable=True),
    sa.Column('instrument_model', sa.String(length=100), nullable=True),
    sa.Column('cell_volume', sa.Float(), nullable=True),
    sa.Column('reference_buffer', sa.String(length=500), nullable=True),
    sa.Column('replicate_number', sa.Integer(), nullable=False),
    sa.Column('replicate_group_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('experiment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['protein_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsc_experiments_compound_id'), 'dsc_experiments', ['compound_id'], unique=False)
    op.create_index('ix_dsc_experiments_compound_target', 'dsc_experiments', ['compound_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_dsc_experiments_experiment_name'), 'dsc_experiments', ['experiment_name'], unique=False)
    op.create_index('ix_dsc_experiments_replicate', 'dsc_experiments', ['replicate_group_id', 'replicate_number'], unique=False)
    op.create_index(op.f('ix_dsc_experiments_replicate_group_id'), 'dsc_experiments', ['replicate_group_id'], unique=False)
    op.create_index(op.f('ix_dsc_experiments_target_id'), 'dsc_experiments', ['target_id'], unique=False)
    op.create_table('mst_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_name', sa.String(length=200), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('target_concentration', sa.Float(), nullable=True),
    sa.Column('ligand_name', sa.String(length=200), nullable=True),
    sa.Column('buffer_composition', sa.String(length=500), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('excitation_power', sa.Float(), nullable=True),
    sa.Column('mst_power', sa.Float(), nullable=True),
    sa.Column('response_units', sa.String(length=50), nullable=False),
    sa.Column('concentration_units', sa.String(length=20), nullable=False),
    sa.Column('kd_value', sa.Float(), nullable=True),
    sa.Column('kd_error', sa.Float(), nullable=True),
    sa.Column('hill_coefficient', sa.Float(), nullable=True),
    sa.Column('binding_amplitude', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('signal_to_noise', sa.Float(), nullable=True),
    sa.Column('aggregation_detected', sa.Boolean(), nullable=False),
    sa.Column('bleaching_rate', sa.Float(), nullable=True),
    sa.Column('instrument_model', sa.String(length=100), nullable=True),
    sa.Column('capillary_type', sa.String(length=50), nullable=True),
    sa.Column('replicate_number', sa.Integer(), nullable=False),
    sa.Column('replicate_group_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('experiment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['protein_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_experiments_compound_id'), 'mst_experiments', ['compound_id'], unique=False)
    op.create_index('ix_mst_experiments_compound_target', 'mst_experiments', ['compound_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_mst_experiments_experiment_name'), 'mst_experiments', ['experiment_name'], unique=False)
    op.create_index('ix_mst_experiments_replicate', 'mst_experiments', ['replicate_group_id', 'replicate_number'], unique=False)
    op.create_index(op.f('ix_mst_experiments_replicate_group_id'), 'mst_experiments', ['replicate_group_id'], unique=False)
    op.create_index(op.f('ix_mst_experiments_target_id'), 'mst_experiments', ['target_id'], unique=False)
    op.create_table('spr_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_name', sa.String(length=200), nullable=False),
    sa.Column('experiment_type', sa.String(length=20), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('analyte_name', sa.String(length=200), nullable=True),
    sa.Column('ligand_name', sa.String(length=200), nullable=True),
    sa.Column('analyte_concentration', sa.Float(), nullable=True),
    sa.Column('ligand_density', sa.Float(), nullable=True),
    sa.Column('buffer_composition', sa.String(length=500), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('response_units', sa.String(length=50), nullable=False),
    sa.Column('concentration_units', sa.String(length=20), nullable=False),
    sa.Column('ka', sa.Float(), nullable=True),
    sa.Column('kd', sa.Float(), nullable=True),
    sa.Column('kd_equilibrium', sa.Float(), nullable=True),
    sa.Column('rmax', sa.Float(), nullable=True),
    sa.Column('chi_squared', sa.Float(), nullable=True),
    sa.Column('baseline_drift', sa.Float(), nullable=True),
    sa.Column('bulk_refractive_index', sa.Float(), nullable=True),
    sa.Column('reference_subtracted', sa.Boolean(), nullable=False),
    sa.Column('instrument_model', sa.String(length=100), nullable=True),
    sa.Column('chip_type', sa.String(length=50), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('replicate_number', sa.Integer(), nullable=False),
    sa.Column('replicate_group_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('experiment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['protein_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spr_experiments_compound_id'), 'spr_experiments', ['compound_id'], unique=False)
    op.create_index('ix_spr_experiments_compound_target', 'spr_experiments', ['compound_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_spr_experiments_experiment_name'), 'spr_experiments', ['experiment_name'], unique=False)
    op.create_index('ix_spr_experiments_replicate', 'spr_experiments', ['replicate_group_id', 'replicate_number'], unique=False)
    op.create_index(op.f('ix_spr_experiments_replicate_group_id'), 'spr_experiments', ['replicate_group_id'], unique=False)
    op.create_index(op.f('ix_spr_experiments_target_id'), 'spr_experiments', ['target_id'], unique=False)
    op.create_table('dsc_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('scan_number', sa.Integer(), nullable=True),
    sa.Column('temperature_celsius', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('heat_capacity', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('baseline_subtracted', sa.Boolean(), nullable=False),
    sa.Column('reference_subtracted', sa.Boolean(), nullable=False),
    sa.Column('normalized', sa.Boolean(), nullable=False),
    sa.Column('data_points_count', sa.Integer(), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['dsc_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsc_scans_experiment_id'), 'dsc_scans', ['experiment_id'], unique=False)
    op.create_index('ix_dsc_scans_experiment_type', 'dsc_scans', ['experiment_id', 'scan_type'], unique=False)
    op.create_table('mst_dose_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('ligand_concentration', sa.Float(), nullable=False),
    sa.Column('thermophoresis_response', sa.Float(), nullable=False),
    sa.Column('thermophoresis_error', sa.Float(), nullable=True),
    sa.Column('initial_fluorescence', sa.Float(), nullable=True),
    sa.Column('thermophoresis_signal', sa.Float(), nullable=True),
    sa.Column('capillary_number', sa.Integer(), nullable=True),
    sa.Column('measurement_valid', sa.Boolean(), nullable=False),
    sa.Column('outlier_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['mst_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mst_dose_responses_experiment_conc', 'mst_dose_responses', ['experiment_id', 'ligand_concentration'], unique=False)
    op.create_index(op.f('ix_mst_dose_responses_experiment_id'), 'mst_dose_responses', ['experiment_id'], unique=False)
    op.create_table('spr_sensorgrams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('cycle_phase', sa.String(length=50), nullable=False),
    sa.Column('flow_cell', sa.Integer(), nullable=True),
    sa.Column('time_seconds', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('response_values', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('baseline_corrected', sa.Boolean(), nullable=False),
    sa.Column('reference_subtracted', sa.Boolean(), nullable=False),
    sa.Column('bulk_shift_corrected', sa.Boolean(), nullable=False),
    sa.Column('data_points_count', sa.Integer(), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['spr_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spr_sensorgrams_experiment_id'), 'spr_sensorgrams', ['experiment_id'], unique=False)
    op.create_index('ix_spr_sensorgrams_experiment_phase', 'spr_sensorgrams', ['experiment_id', 'cycle_phase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spr_sensorgrams_experiment_phase', table_name='spr_sensorgrams')
    op.drop_index(op.f('ix_spr_sensorgrams_experiment_id'), table_name='spr_sensorgrams')
    op.drop_table('spr_sensorgrams')
    op.drop_index(op.f('ix_mst_dose_responses_experiment_id'), table_name='mst_dose_responses')
    op.drop_index('ix_mst_dose_responses_experiment_conc', table_name='mst_dose_responses')
    op.drop_table('mst_dose_responses')
    op.drop_index('ix_dsc_scans_experiment_type', table_name='dsc_scans')
    op.drop_index(op.f('ix_dsc_scans_experiment_id'), table_name='dsc_scans')
    op.drop_table('dsc_scans')
    op.drop_index(op.f('ix_spr_experiments_target_id'), table_name='spr_experiments')
    op.drop_index(op.f('ix_spr_experiments_replicate_group_id'), table_name='spr_experiments')
    op.drop_index('ix_spr_experiments_replicate', table_name='spr_experiments')
    op.drop_index(op.f('ix_spr_experiments_experiment_name'), table_name='spr_experiments')
    op.drop_index('ix_spr_experiments_compound_target', table_name='spr_experiments')
    op.drop_index(op.f('ix_spr_experiments_compound_id'), table_name='spr_experiments')
    op.drop_table('spr_experiments')
    op.drop_index(op.f('ix_mst_experiments_target_id'), table_name='mst_experiments')
    op.drop_index(op.f('ix_mst_experiments_replicate_group_id'), table_name='mst_experiments')
    op.drop_index('ix_mst_experiments_replicate', table_name='mst_experiments')
    op.drop_index(op.f('ix_mst_experiments_experiment_name'), table_name='mst_experiments')
    op.drop_index('ix_mst_experiments_compound_target', table_name='mst_experiments')
    op.drop_index(op.f('ix_mst_experiments_compound_id'), table_name='mst_experiments')
    op.drop_table('mst_experiments')
    op.drop_index(op.f('ix_dsc_experiments_target_id'), table_name='dsc_experiments')
    op.drop_index(op.f('ix_dsc_experiments_replicate_group_id'), table_name='dsc_experiments')
    op.drop_index('ix_dsc_experiments_replicate', table_name='dsc_experiments')
    op.drop_index(op.f('ix_dsc_experiments_experiment_name'), table_name='dsc_experiments')
    op.drop_index('ix_dsc_experiments_compound_target', table_name='dsc_experiments')
    op.drop_index(op.f('ix_dsc_experiments_compound_id'), table_name='dsc_experiments')
    op.drop_table('dsc_experiments')
    # ### end Alembic commands ###

