"""add alignment_files table

Revision ID: 772e7a60db92
Revises: 6b8390d65453
Create Date: 2026-01-01 19:19:39.449584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772e7a60db92'
down_revision = '6b8390d65453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alignment_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('index_file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('has_index', sa.Boolean(), nullable=False),
    sa.Column('reference_genome', sa.String(length=100), nullable=True),
    sa.Column('num_references', sa.Integer(), nullable=True),
    sa.Column('read_groups', sa.JSON(), nullable=True),
    sa.Column('total_reads', sa.Integer(), nullable=True),
    sa.Column('mapped_reads', sa.Integer(), nullable=True),
    sa.Column('unmapped_reads', sa.Integer(), nullable=True),
    sa.Column('duplicate_rate', sa.Float(), nullable=True),
    sa.Column('mean_coverage', sa.Float(), nullable=True),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alignment_files_experiment_id'), 'alignment_files', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_alignment_files_has_index'), 'alignment_files', ['has_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alignment_files_has_index'), table_name='alignment_files')
    op.drop_index(op.f('ix_alignment_files_experiment_id'), table_name='alignment_files')
    op.drop_table('alignment_files')
    # ### end Alembic commands ###

