"""add share_links table

Revision ID: 7b9ea73469db
Revises: c08bd9a2f1a9
Create Date: 2025-12-29 17:47:39.535584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9ea73469db'
down_revision = 'c08bd9a2f1a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invention_disclosures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technical_field', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority_date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invention_disclosures_company_id'), 'invention_disclosures', ['company_id'], unique=False)
    op.create_index('ix_invention_disclosures_company_status', 'invention_disclosures', ['company_id', 'status'], unique=False)
    op.create_index('ix_invention_disclosures_priority_date', 'invention_disclosures', ['priority_date'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('dashboard_path', sa.String(length=500), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_share_links_company_active', 'share_links', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_share_links_company_id'), 'share_links', ['company_id'], unique=False)
    op.create_index('ix_share_links_expires', 'share_links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_table('disclosure_inventors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disclosure_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contribution_percentage', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['invention_disclosures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosure_inventors_disclosure_id'), 'disclosure_inventors', ['disclosure_id'], unique=False)
    op.create_table('ip_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('disclosure_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['invention_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'disclosure_id', 'link_type', name='uq_ip_links')
    )
    op.create_index(op.f('ix_ip_links_disclosure_id'), 'ip_links', ['disclosure_id'], unique=False)
    op.create_index('ix_ip_links_entity', 'ip_links', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_ip_links_entity_id'), 'ip_links', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ip_links_entity_type'), 'ip_links', ['entity_type'], unique=False)
    op.create_table('patent_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disclosure_id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=100), nullable=False),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('grant_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['invention_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_applications_disclosure_id'), 'patent_applications', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_patent_applications_status'), 'patent_applications', ['status'], unique=False)
    op.create_table('patent_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patent_id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('parent_claim_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_claim_id'], ['patent_claims.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patent_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_claims_patent_id'), 'patent_claims', ['patent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patent_claims_patent_id'), table_name='patent_claims')
    op.drop_table('patent_claims')
    op.drop_index(op.f('ix_patent_applications_status'), table_name='patent_applications')
    op.drop_index(op.f('ix_patent_applications_disclosure_id'), table_name='patent_applications')
    op.drop_table('patent_applications')
    op.drop_index(op.f('ix_ip_links_entity_type'), table_name='ip_links')
    op.drop_index(op.f('ix_ip_links_entity_id'), table_name='ip_links')
    op.drop_index('ix_ip_links_entity', table_name='ip_links')
    op.drop_index(op.f('ix_ip_links_disclosure_id'), table_name='ip_links')
    op.drop_table('ip_links')
    op.drop_index(op.f('ix_disclosure_inventors_disclosure_id'), table_name='disclosure_inventors')
    op.drop_table('disclosure_inventors')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index('ix_share_links_expires', table_name='share_links')
    op.drop_index(op.f('ix_share_links_company_id'), table_name='share_links')
    op.drop_index('ix_share_links_company_active', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('ix_invention_disclosures_priority_date', table_name='invention_disclosures')
    op.drop_index('ix_invention_disclosures_company_status', table_name='invention_disclosures')
    op.drop_index(op.f('ix_invention_disclosures_company_id'), table_name='invention_disclosures')
    op.drop_table('invention_disclosures')
    # ### end Alembic commands ###

