"""add review cycles and sla models

Revision ID: 804a93b1af9d
Revises: f7a6befef808
Create Date: 2025-12-31 16:55:51.382643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804a93b1af9d'
down_revision = 'f7a6befef808'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_slas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('max_review_hours', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('escalation_chain', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_slas_entity_type', 'review_slas', ['entity_type'], unique=False)
    op.create_table('review_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_pool', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_cycles_entity_type', 'review_cycles', ['entity_type'], unique=False)
    op.create_index('ix_review_cycles_next_run', 'review_cycles', ['next_run_at'], unique=False)
    op.add_column('entity_reviews', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entity_reviews', sa.Column('sla_id', sa.UUID(), nullable=True))
    op.add_column('entity_reviews', sa.Column('cycle_id', sa.UUID(), nullable=True))
    op.add_column('entity_reviews', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entity_reviews', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entity_reviews', sa.Column('escalation_level', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'entity_reviews', 'review_slas', ['sla_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entity_reviews', 'review_cycles', ['cycle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_reviews', type_='foreignkey')
    op.drop_constraint(None, 'entity_reviews', type_='foreignkey')
    op.drop_column('entity_reviews', 'escalation_level')
    op.drop_column('entity_reviews', 'escalated_at')
    op.drop_column('entity_reviews', 'reminder_sent_at')
    op.drop_column('entity_reviews', 'cycle_id')
    op.drop_column('entity_reviews', 'sla_id')
    op.drop_column('entity_reviews', 'due_at')
    op.drop_index('ix_review_cycles_next_run', table_name='review_cycles')
    op.drop_index('ix_review_cycles_entity_type', table_name='review_cycles')
    op.drop_table('review_cycles')
    op.drop_index('ix_review_slas_entity_type', table_name='review_slas')
    op.drop_table('review_slas')
    # ### end Alembic commands ###

