"""add inline_annotations table

Revision ID: 8877d15d1426
Revises: 804a93b1af9d
Create Date: 2025-12-31 18:29:06.546877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8877d15d1426'
down_revision = '804a93b1af9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inline_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('position_type', sa.String(length=30), nullable=False),
    sa.Column('position_data', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['inline_annotations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inline_annotations_entity', 'inline_annotations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_inline_annotations_entity_id'), 'inline_annotations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_inline_annotations_entity_type'), 'inline_annotations', ['entity_type'], unique=False)
    op.create_index('ix_inline_annotations_position_type', 'inline_annotations', ['position_type'], unique=False)
    op.create_index('ix_inline_annotations_status', 'inline_annotations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inline_annotations_status', table_name='inline_annotations')
    op.drop_index('ix_inline_annotations_position_type', table_name='inline_annotations')
    op.drop_index(op.f('ix_inline_annotations_entity_type'), table_name='inline_annotations')
    op.drop_index(op.f('ix_inline_annotations_entity_id'), table_name='inline_annotations')
    op.drop_index('ix_inline_annotations_entity', table_name='inline_annotations')
    op.drop_table('inline_annotations')
    # ### end Alembic commands ###

