"""add_compound_inventory_models

Revision ID: 892e9030b093
Revises: 65947a84ef25
Create Date: 2026-01-03 03:53:46.288055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892e9030b093'
down_revision = '65947a84ef25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound_plates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=False),
    sa.Column('plate_format', sa.String(length=20), nullable=False),
    sa.Column('plate_type', sa.String(length=50), nullable=False),
    sa.Column('storage_location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compound_plates_barcode'), 'compound_plates', ['barcode'], unique=True)
    op.create_table('compound_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compound_requests_compound_id'), 'compound_requests', ['compound_id'], unique=False)
    op.create_index(op.f('ix_compound_requests_requester_id'), 'compound_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_compound_requests_sample_id'), 'compound_requests', ['sample_id'], unique=False)
    op.add_column('samples', sa.Column('compound_id', sa.UUID(), nullable=True))
    op.add_column('samples', sa.Column('concentration', sa.Float(), nullable=True))
    op.add_column('samples', sa.Column('concentration_unit', sa.String(length=20), nullable=True))
    op.add_column('samples', sa.Column('solvent', sa.String(length=50), nullable=True))
    op.add_column('samples', sa.Column('format', sa.String(length=20), nullable=True))
    op.add_column('samples', sa.Column('batch_lot', sa.String(length=100), nullable=True))
    op.add_column('samples', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('samples', sa.Column('plate_id', sa.UUID(), nullable=True))
    op.add_column('samples', sa.Column('well_position', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_samples_compound_id'), 'samples', ['compound_id'], unique=False)
    op.create_index(op.f('ix_samples_plate_id'), 'samples', ['plate_id'], unique=False)
    op.create_foreign_key(None, 'samples', 'compounds', ['compound_id'], ['id'])
    op.create_foreign_key(None, 'samples', 'compound_plates', ['plate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_index(op.f('ix_samples_plate_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_compound_id'), table_name='samples')
    op.drop_column('samples', 'well_position')
    op.drop_column('samples', 'plate_id')
    op.drop_column('samples', 'expiry_date')
    op.drop_column('samples', 'batch_lot')
    op.drop_column('samples', 'format')
    op.drop_column('samples', 'solvent')
    op.drop_column('samples', 'concentration_unit')
    op.drop_column('samples', 'concentration')
    op.drop_column('samples', 'compound_id')
    op.drop_index(op.f('ix_compound_requests_sample_id'), table_name='compound_requests')
    op.drop_index(op.f('ix_compound_requests_requester_id'), table_name='compound_requests')
    op.drop_index(op.f('ix_compound_requests_compound_id'), table_name='compound_requests')
    op.drop_table('compound_requests')
    op.drop_index(op.f('ix_compound_plates_barcode'), table_name='compound_plates')
    op.drop_table('compound_plates')
    # ### end Alembic commands ###

