"""add publication extraction tables

Revision ID: 8f4f671e4f2f
Revises: 68c84053ba9a
Create Date: 2025-12-29 05:29:35.981206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f4f671e4f2f'
down_revision = '68c84053ba9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('literature_id', sa.UUID(), nullable=False),
    sa.Column('experiment_type', sa.String(length=200), nullable=False),
    sa.Column('cell_line', sa.String(length=200), nullable=True),
    sa.Column('treatment', sa.String(length=500), nullable=True),
    sa.Column('concentration', sa.String(length=100), nullable=True),
    sa.Column('timepoint', sa.String(length=100), nullable=True),
    sa.Column('replicate_count', sa.Integer(), nullable=True),
    sa.Column('measured_entities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('key_findings', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_extractions_literature_id'), 'publication_extractions', ['literature_id'], unique=False)
    op.create_table('supplementary_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('literature_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('schema_type', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('columns', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('linked_dataset_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplementary_files_linked_dataset_id'), 'supplementary_files', ['linked_dataset_id'], unique=False)
    op.create_index(op.f('ix_supplementary_files_literature_id'), 'supplementary_files', ['literature_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplementary_files_literature_id'), table_name='supplementary_files')
    op.drop_index(op.f('ix_supplementary_files_linked_dataset_id'), table_name='supplementary_files')
    op.drop_table('supplementary_files')
    op.drop_index(op.f('ix_publication_extractions_literature_id'), table_name='publication_extractions')
    op.drop_table('publication_extractions')
    # ### end Alembic commands ###

