"""add_entity_versions_table

Revision ID: 905db1b1ee79
Revises: 054c475bc908
Create Date: 2025-12-31 04:56:09.179229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '905db1b1ee79'
down_revision = '054c475bc908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'version_number', name='uq_entity_version')
    )
    op.create_index(op.f('ix_entity_versions_entity_id'), 'entity_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_versions_entity_type'), 'entity_versions', ['entity_type'], unique=False)
    op.create_index('ix_entity_versions_lookup', 'entity_versions', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_versions_lookup', table_name='entity_versions')
    op.drop_index(op.f('ix_entity_versions_entity_type'), table_name='entity_versions')
    op.drop_index(op.f('ix_entity_versions_entity_id'), table_name='entity_versions')
    op.drop_table('entity_versions')
    # ### end Alembic commands ###

