"""add entity sharing and review models

Revision ID: 98894b17e636
Revises: b5d4975de50f
Create Date: 2025-12-28 07:25:56.766552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98894b17e636'
down_revision = 'b5d4975de50f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_reviews_entity', 'entity_reviews', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_entity_reviews_reviewer', 'entity_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_entity_reviews_status', 'entity_reviews', ['status'], unique=False)
    op.create_table('entity_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=True),
    sa.Column('shared_with_team_id', sa.UUID(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('shared_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(shared_with_user_id IS NULL) != (shared_with_team_id IS NULL)', name='ck_entity_shares_xor_user_team'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_shares_entity', 'entity_shares', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_entity_shares_team', 'entity_shares', ['shared_with_team_id'], unique=False)
    op.create_index('ix_entity_shares_user', 'entity_shares', ['shared_with_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_shares_user', table_name='entity_shares')
    op.drop_index('ix_entity_shares_team', table_name='entity_shares')
    op.drop_index('ix_entity_shares_entity', table_name='entity_shares')
    op.drop_table('entity_shares')
    op.drop_index('ix_entity_reviews_status', table_name='entity_reviews')
    op.drop_index('ix_entity_reviews_reviewer', table_name='entity_reviews')
    op.drop_index('ix_entity_reviews_entity', table_name='entity_reviews')
    op.drop_table('entity_reviews')
    # ### end Alembic commands ###

