"""add ip tracking tables

Revision ID: 9ab78faa6cce
Revises: e32eb04dd92e
Create Date: 2025-12-29 17:12:30.546927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab78faa6cce'
down_revision = 'e32eb04dd92e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

