"""add_activity_events_notifications

Revision ID: a2b3c4d5e6f9
Revises: a1b2c3d4e5f8
Create Date: 2025-12-27 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2b3c4d5e6f9'
down_revision = 'a1b2c3d4e5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Rename alerts table to repository_notifications
    op.rename_table('alerts', 'repository_notifications')
    
    # 2. Make existing columns nullable for activity-based notifications
    op.alter_column('repository_notifications', 'subscription_id', nullable=True)
    op.alter_column('repository_notifications', 'dataset_id', nullable=True)
    
    # 3. Add new columns to repository_notifications table
    op.add_column('repository_notifications', sa.Column('activity_event_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('repository_notifications', sa.Column('notification_type', sa.String(length=50), nullable=True))
    
    # 4. Backfill notification_type for existing records
    op.execute("UPDATE repository_notifications SET notification_type='discovery' WHERE notification_type IS NULL")
    
    # 5. Create activity_events table
    op.create_table('activity_events',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('actor_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('target_type', sa.String(length=50), nullable=True),
        sa.Column('target_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('target_name', sa.String(length=255), nullable=True),
        sa.Column('program_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('event_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for activity_events
    op.create_index(op.f('ix_activity_events_event_type'), 'activity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_events_actor_id'), 'activity_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_events_target_type'), 'activity_events', ['target_type'], unique=False)
    op.create_index(op.f('ix_activity_events_target_id'), 'activity_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_activity_events_program_id'), 'activity_events', ['program_id'], unique=False)
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    
    # 6. Add FK constraint: repository_notifications.activity_event_id → activity_events.id
    op.create_foreign_key('fk_repository_notifications_activity_event_id', 'repository_notifications', 'activity_events', ['activity_event_id'], ['id'])
    op.create_index(op.f('ix_repository_notifications_activity_event_id'), 'repository_notifications', ['activity_event_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop FK constraint and index for repository_notifications.activity_event_id
    op.drop_index(op.f('ix_repository_notifications_activity_event_id'), table_name='repository_notifications')
    op.drop_constraint('fk_repository_notifications_activity_event_id', 'repository_notifications', type_='foreignkey')
    
    # Drop activity_events table and its indexes
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_program_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_target_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_target_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_actor_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_event_type'), table_name='activity_events')
    op.drop_table('activity_events')
    
    # Remove new columns from repository_notifications
    op.drop_column('repository_notifications', 'notification_type')
    op.drop_column('repository_notifications', 'activity_event_id')
    
    # Revert nullable changes
    op.alter_column('repository_notifications', 'subscription_id', nullable=False)
    op.alter_column('repository_notifications', 'dataset_id', nullable=False)
    
    # Rename repository_notifications table back to alerts
    op.rename_table('repository_notifications', 'alerts')
    
    # ### end Alembic commands ###
