"""add flow cytometry tables

Revision ID: a455cf9a1bef
Revises: 0e1ddc8868e5
Create Date: 2025-12-30 09:04:36.913994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a455cf9a1bef'
down_revision = '0e1ddc8868e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_cytometry_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('events_parquet_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('n_events', sa.Integer(), nullable=True),
    sa.Column('n_parameters', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cytometer_model', sa.String(length=200), nullable=True),
    sa.Column('cytometer_serial', sa.String(length=100), nullable=True),
    sa.Column('acquisition_software', sa.String(length=100), nullable=True),
    sa.Column('acquisition_settings', sa.JSON(), nullable=True),
    sa.Column('sample_id', sa.String(length=200), nullable=True),
    sa.Column('sample_volume_ul', sa.Float(), nullable=True),
    sa.Column('dilution_factor', sa.Float(), nullable=True),
    sa.Column('staining_protocol', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_cytometry_datasets_dataset_id'), 'flow_cytometry_datasets', ['dataset_id'], unique=False)
    op.create_table('flow_cytometry_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_dataset_id', sa.UUID(), nullable=False),
    sa.Column('parameter_index', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_short_name', sa.String(length=50), nullable=True),
    sa.Column('detector', sa.String(length=100), nullable=True),
    sa.Column('excitation_wavelength', sa.Integer(), nullable=True),
    sa.Column('emission_wavelength', sa.Integer(), nullable=True),
    sa.Column('fluorophore', sa.String(length=100), nullable=True),
    sa.Column('data_range', sa.Integer(), nullable=True),
    sa.Column('amplifier_gain', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['flow_dataset_id'], ['flow_cytometry_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_dataset_id', 'parameter_index', name='uq_flow_parameter_index')
    )
    op.create_index(op.f('ix_flow_cytometry_parameters_flow_dataset_id'), 'flow_cytometry_parameters', ['flow_dataset_id'], unique=False)
    op.create_index('ix_flow_parameters_dataset_name', 'flow_cytometry_parameters', ['flow_dataset_id', 'parameter_name'], unique=False)
    op.create_table('flow_cytometry_gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_dataset_id', sa.UUID(), nullable=False),
    sa.Column('gate_name', sa.String(length=200), nullable=False),
    sa.Column('gate_type', sa.String(length=20), nullable=False),
    sa.Column('gate_definition', sa.JSON(), nullable=False),
    sa.Column('x_parameter_id', sa.UUID(), nullable=False),
    sa.Column('y_parameter_id', sa.UUID(), nullable=True),
    sa.Column('boolean_operator', sa.String(length=10), nullable=True),
    sa.Column('operand_gate_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('parent_gate_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flow_dataset_id'], ['flow_cytometry_datasets.id'], ),
    sa.ForeignKeyConstraint(['parent_gate_id'], ['flow_cytometry_gates.id'], ),
    sa.ForeignKeyConstraint(['x_parameter_id'], ['flow_cytometry_parameters.id'], ),
    sa.ForeignKeyConstraint(['y_parameter_id'], ['flow_cytometry_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_cytometry_gates_flow_dataset_id'), 'flow_cytometry_gates', ['flow_dataset_id'], unique=False)
    op.create_index('ix_flow_gates_dataset_name', 'flow_cytometry_gates', ['flow_dataset_id', 'gate_name'], unique=False)
    op.create_index('ix_flow_gates_parent', 'flow_cytometry_gates', ['parent_gate_id'], unique=False)
    op.create_table('flow_cytometry_populations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flow_dataset_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('parent_event_count', sa.Integer(), nullable=True),
    sa.Column('percentage_of_parent', sa.Float(), nullable=True),
    sa.Column('percentage_of_total', sa.Float(), nullable=True),
    sa.Column('population_name', sa.String(length=200), nullable=True),
    sa.Column('cell_type', sa.String(length=200), nullable=True),
    sa.Column('phenotype', sa.String(length=500), nullable=True),
    sa.Column('parameter_statistics', sa.JSON(), nullable=True),
    sa.Column('analysis_software', sa.String(length=100), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flow_dataset_id'], ['flow_cytometry_datasets.id'], ),
    sa.ForeignKeyConstraint(['gate_id'], ['flow_cytometry_gates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_dataset_id', 'gate_id', name='uq_flow_population_gate')
    )
    op.create_index(op.f('ix_flow_cytometry_populations_flow_dataset_id'), 'flow_cytometry_populations', ['flow_dataset_id'], unique=False)
    op.create_index(op.f('ix_flow_cytometry_populations_gate_id'), 'flow_cytometry_populations', ['gate_id'], unique=False)
    op.create_index('ix_flow_populations_dataset_gate', 'flow_cytometry_populations', ['flow_dataset_id', 'gate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_populations_dataset_gate', table_name='flow_cytometry_populations')
    op.drop_index(op.f('ix_flow_cytometry_populations_gate_id'), table_name='flow_cytometry_populations')
    op.drop_index(op.f('ix_flow_cytometry_populations_flow_dataset_id'), table_name='flow_cytometry_populations')
    op.drop_table('flow_cytometry_populations')
    op.drop_index('ix_flow_gates_parent', table_name='flow_cytometry_gates')
    op.drop_index('ix_flow_gates_dataset_name', table_name='flow_cytometry_gates')
    op.drop_index(op.f('ix_flow_cytometry_gates_flow_dataset_id'), table_name='flow_cytometry_gates')
    op.drop_table('flow_cytometry_gates')
    op.drop_index('ix_flow_parameters_dataset_name', table_name='flow_cytometry_parameters')
    op.drop_index(op.f('ix_flow_cytometry_parameters_flow_dataset_id'), table_name='flow_cytometry_parameters')
    op.drop_table('flow_cytometry_parameters')
    op.drop_index(op.f('ix_flow_cytometry_datasets_dataset_id'), table_name='flow_cytometry_datasets')
    op.drop_table('flow_cytometry_datasets')
    # ### end Alembic commands ###

