"""add data catalog models

Revision ID: a6703730fbfc
Revises: cf71ba2db1bd
Create Date: 2026-01-03 06:20:25.114810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6703730fbfc'
down_revision = 'cf71ba2db1bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type')
    )
    op.create_table('data_lineage_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('transformation', sa.String(length=200), nullable=True),
    sa.Column('edge_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', name='uix_lineage_source_target')
    )
    op.create_index('ix_lineage_source', 'data_lineage_edges', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_lineage_target', 'data_lineage_edges', ['target_type', 'target_id'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('column_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_entry_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_foreign_key', sa.Boolean(), nullable=False),
    sa.Column('foreign_key_target', sa.String(length=200), nullable=True),
    sa.Column('example_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('glossary_term_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_entry_id'], ['catalog_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['glossary_term_id'], ['glossary_terms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_entry_id', 'column_name', name='uix_column_entry_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_metadata')
    op.drop_table('glossary_terms')
    op.drop_index('ix_lineage_target', table_name='data_lineage_edges')
    op.drop_index('ix_lineage_source', table_name='data_lineage_edges')
    op.drop_table('data_lineage_edges')
    op.drop_table('catalog_entries')
    # ### end Alembic commands ###

