"""add target model and compound_target association

Revision ID: a7a1b2e2e8de
Revises: aea7b4fd12f7
Create Date: 2026-01-02 16:41:30.901852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7a1b2e2e8de'
down_revision = 'aea7b4fd12f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gene_symbol', sa.String(length=50), nullable=True),
    sa.Column('uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('target_class', sa.String(length=100), nullable=True),
    sa.Column('target_family', sa.String(length=100), nullable=True),
    sa.Column('druggability_score', sa.Float(), nullable=True),
    sa.Column('druggability_source', sa.String(length=50), nullable=True),
    sa.Column('pocket_count', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_evidence', sa.JSON(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('chembl_id', sa.String(length=50), nullable=True),
    sa.Column('ensembl_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_targets_gene_symbol'), 'targets', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_targets_uniprot_id'), 'targets', ['uniprot_id'], unique=False)
    op.create_table('compound_target',
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('activity_value', sa.Float(), nullable=True),
    sa.Column('activity_units', sa.String(length=20), nullable=True),
    sa.Column('assay_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('compound_id', 'target_id')
    )
    op.drop_index(op.f('ix_lockout_identifier'), table_name='auth_lockout_attempts')
    op.drop_index(op.f('ix_lockout_identifier_time'), table_name='auth_lockout_attempts')
    op.drop_table('auth_lockout_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_lockout_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attempt_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_lockout_attempts_pkey'))
    )
    op.create_index(op.f('ix_lockout_identifier_time'), 'auth_lockout_attempts', ['identifier', 'attempt_time'], unique=False)
    op.create_index(op.f('ix_lockout_identifier'), 'auth_lockout_attempts', ['identifier'], unique=False)
    op.drop_table('compound_target')
    op.drop_index(op.f('ix_targets_uniprot_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_gene_symbol'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###

