"""add_missing_schema_elements

Revision ID: b5d4975de50f
Revises: e9386d67cc54
Create Date: 2025-12-27 19:15:13.899091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5d4975de50f'
down_revision = 'e9386d67cc54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_datasets', sa.Integer(), nullable=True),
    sa.Column('storage_quota_gb', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_index(op.f('ix_companies_subdomain'), 'companies', ['subdomain'], unique=True)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_batch_id'), 'extraction_jobs', ['batch_id'], unique=False)
    op.create_index('ix_extraction_jobs_batch_status', 'extraction_jobs', ['batch_id', 'status'], unique=False)
    op.create_index('ix_extraction_jobs_status', 'extraction_jobs', ['status'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_source', sa.String(length=100), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_type', 'source_entity_id', 'target_entity_type', 'target_entity_id', 'relationship_type', 'evidence_source', name='uq_graph_edge')
    )
    op.create_index(op.f('ix_graph_edges_evidence_source'), 'graph_edges', ['evidence_source'], unique=False)
    op.create_index(op.f('ix_graph_edges_relationship_type'), 'graph_edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_entity_id'), 'graph_edges', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_entity_type'), 'graph_edges', ['source_entity_type'], unique=False)
    op.create_index('ix_graph_edges_src_rel', 'graph_edges', ['source_entity_type', 'source_entity_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_entity_id'), 'graph_edges', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_entity_type'), 'graph_edges', ['target_entity_type'], unique=False)
    op.create_index('ix_graph_edges_tgt_rel', 'graph_edges', ['target_entity_type', 'target_entity_id', 'relationship_type'], unique=False)
    op.create_table('lincs_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sig_id', sa.String(length=100), nullable=False),
    sa.Column('pert_iname', sa.String(length=200), nullable=True),
    sa.Column('pert_id', sa.String(length=100), nullable=True),
    sa.Column('pert_type', sa.String(length=100), nullable=True),
    sa.Column('cell_id', sa.String(length=100), nullable=True),
    sa.Column('pert_time', sa.Float(), nullable=True),
    sa.Column('pert_dose', sa.Float(), nullable=True),
    sa.Column('gene_expression', sa.JSON(), nullable=True),
    sa.Column('tas', sa.Float(), nullable=True),
    sa.Column('distil_id', sa.String(length=500), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lincs_signatures_cell_id'), 'lincs_signatures', ['cell_id'], unique=False)
    op.create_index(op.f('ix_lincs_signatures_pert_id'), 'lincs_signatures', ['pert_id'], unique=False)
    op.create_index(op.f('ix_lincs_signatures_pert_iname'), 'lincs_signatures', ['pert_iname'], unique=False)
    op.create_index(op.f('ix_lincs_signatures_sig_id'), 'lincs_signatures', ['sig_id'], unique=True)
    op.create_table('multi_omics_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_ids', sa.JSON(), nullable=True),
    sa.Column('sample_mapping', sa.JSON(), nullable=True),
    sa.Column('n_factors', sa.Integer(), nullable=True),
    sa.Column('convergence_mode', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multi_omics_experiments_name'), 'multi_omics_experiments', ['name'], unique=False)
    op.create_index(op.f('ix_multi_omics_experiments_status'), 'multi_omics_experiments', ['status'], unique=False)
    op.create_table('phenotype_gene_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hpo_id', sa.String(length=20), nullable=False),
    sa.Column('hpo_name', sa.String(length=500), nullable=True),
    sa.Column('gene_symbol', sa.String(length=50), nullable=False),
    sa.Column('ncbi_gene_id', sa.String(length=30), nullable=True),
    sa.Column('disease_id', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hpo_id', 'gene_symbol', 'disease_id', name='uq_hpo_gene_disease')
    )
    op.create_index(op.f('ix_phenotype_gene_associations_gene_symbol'), 'phenotype_gene_associations', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_phenotype_gene_associations_hpo_id'), 'phenotype_gene_associations', ['hpo_id'], unique=False)
    op.create_table('spectral_libraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('n_spectra', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_spectral_library_name_version')
    )
    op.create_index(op.f('ix_spectral_libraries_name'), 'spectral_libraries', ['name'], unique=False)
    op.create_index(op.f('ix_spectral_libraries_version'), 'spectral_libraries', ['version'], unique=False)
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('conflicts_detected', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_source'), 'sync_jobs', ['source'], unique=False)
    op.create_index('ix_sync_jobs_source_status', 'sync_jobs', ['source', 'status'], unique=False)
    op.create_index(op.f('ix_sync_jobs_status'), 'sync_jobs', ['status'], unique=False)
    op.create_table('variant_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('n_variants', sa.Integer(), nullable=True),
    sa.Column('n_genes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_sets_name'), 'variant_sets', ['name'], unique=False)
    op.create_index(op.f('ix_variant_sets_source_type'), 'variant_sets', ['source_type'], unique=False)
    op.create_index(op.f('ix_variant_sets_status'), 'variant_sets', ['status'], unique=False)
    op.create_table('chembl_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('chembl_molecule_id', sa.String(length=50), nullable=False),
    sa.Column('chembl_assay_id', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('relation', sa.String(length=10), nullable=True),
    sa.Column('target_chembl_id', sa.String(length=50), nullable=True),
    sa.Column('target_name', sa.String(length=500), nullable=True),
    sa.Column('assay_type', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chembl_activities_chembl_assay_id'), 'chembl_activities', ['chembl_assay_id'], unique=False)
    op.create_index(op.f('ix_chembl_activities_chembl_molecule_id'), 'chembl_activities', ['chembl_molecule_id'], unique=False)
    op.create_index(op.f('ix_chembl_activities_compound_id'), 'chembl_activities', ['compound_id'], unique=False)
    op.create_index('ix_chembl_activities_molecule_assay', 'chembl_activities', ['chembl_molecule_id', 'chembl_assay_id'], unique=False)
    op.create_index(op.f('ix_chembl_activities_target_chembl_id'), 'chembl_activities', ['target_chembl_id'], unique=False)
    op.create_table('extracted_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_documents_doc_type'), 'extracted_documents', ['doc_type'], unique=False)
    op.create_index('ix_extracted_documents_job_doc_type', 'extracted_documents', ['job_id', 'doc_type'], unique=False)
    op.create_index(op.f('ix_extracted_documents_job_id'), 'extracted_documents', ['job_id'], unique=False)
    op.create_index('ix_extracted_documents_job_status', 'extracted_documents', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_extracted_documents_status'), 'extracted_documents', ['status'], unique=False)
    op.create_table('gene_burdens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_set_id', sa.UUID(), nullable=False),
    sa.Column('gene_symbol', sa.String(length=100), nullable=True),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('n_variants', sa.Integer(), nullable=True),
    sa.Column('n_pathogenic', sa.Integer(), nullable=True),
    sa.Column('n_vus', sa.Integer(), nullable=True),
    sa.Column('n_benign', sa.Integer(), nullable=True),
    sa.Column('burden_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['variant_set_id'], ['variant_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_set_id', 'gene_symbol', name='uq_gene_burden_set_gene')
    )
    op.create_index(op.f('ix_gene_burdens_feature_id'), 'gene_burdens', ['feature_id'], unique=False)
    op.create_index(op.f('ix_gene_burdens_gene_symbol'), 'gene_burdens', ['gene_symbol'], unique=False)
    op.create_index('ix_gene_burdens_set_gene', 'gene_burdens', ['variant_set_id', 'gene_symbol'], unique=False)
    op.create_index(op.f('ix_gene_burdens_variant_set_id'), 'gene_burdens', ['variant_set_id'], unique=False)
    op.create_table('latent_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('factor_index', sa.Integer(), nullable=False),
    sa.Column('variance_explained', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['multi_omics_experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'factor_index', name='uq_latent_factor_experiment_index')
    )
    op.create_index(op.f('ix_latent_factors_experiment_id'), 'latent_factors', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_latent_factors_factor_index'), 'latent_factors', ['factor_index'], unique=False)
    op.create_table('lincs_genes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrez_id', sa.Integer(), nullable=False),
    sa.Column('gene_symbol', sa.String(length=50), nullable=True),
    sa.Column('gene_title', sa.String(length=500), nullable=True),
    sa.Column('is_landmark', sa.Boolean(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lincs_genes_entrez_id'), 'lincs_genes', ['entrez_id'], unique=True)
    op.create_index(op.f('ix_lincs_genes_feature_id'), 'lincs_genes', ['feature_id'], unique=False)
    op.create_index(op.f('ix_lincs_genes_gene_symbol'), 'lincs_genes', ['gene_symbol'], unique=False)
    op.create_table('protein_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('pdb_id', sa.String(length=10), nullable=True),
    sa.Column('alphafold_uniprot_id', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('chain_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('prep_status', sa.String(length=50), nullable=True),
    sa.Column('prep_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protein_structures_alphafold_uniprot_id'), 'protein_structures', ['alphafold_uniprot_id'], unique=False)
    op.create_index(op.f('ix_protein_structures_feature_id'), 'protein_structures', ['feature_id'], unique=False)
    op.create_index(op.f('ix_protein_structures_pdb_id'), 'protein_structures', ['pdb_id'], unique=False)
    op.create_table('pubchem_bioassays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=True),
    sa.Column('pubchem_cid', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('activity_outcome', sa.String(length=50), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('assay_name', sa.String(length=500), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pubchem_bioassays_aid'), 'pubchem_bioassays', ['aid'], unique=False)
    op.create_index('ix_pubchem_bioassays_cid_aid', 'pubchem_bioassays', ['pubchem_cid', 'aid'], unique=False)
    op.create_index(op.f('ix_pubchem_bioassays_compound_id'), 'pubchem_bioassays', ['compound_id'], unique=False)
    op.create_index(op.f('ix_pubchem_bioassays_pubchem_cid'), 'pubchem_bioassays', ['pubchem_cid'], unique=False)
    op.create_table('spectral_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('lipid_name', sa.String(length=500), nullable=False),
    sa.Column('lipid_class', sa.String(length=200), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('inchi_key', sa.String(length=50), nullable=True),
    sa.Column('precursor_mz', sa.Float(), nullable=False),
    sa.Column('precursor_type', sa.String(length=50), nullable=True),
    sa.Column('collision_energy', sa.Float(), nullable=True),
    sa.Column('spectrum', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['spectral_libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spectral_ref_library_precursor', 'spectral_references', ['library_id', 'precursor_mz'], unique=False)
    op.create_index(op.f('ix_spectral_references_inchi_key'), 'spectral_references', ['inchi_key'], unique=False)
    op.create_index(op.f('ix_spectral_references_library_id'), 'spectral_references', ['library_id'], unique=False)
    op.create_index(op.f('ix_spectral_references_lipid_class'), 'spectral_references', ['lipid_class'], unique=False)
    op.create_index(op.f('ix_spectral_references_lipid_name'), 'spectral_references', ['lipid_name'], unique=False)
    op.create_index(op.f('ix_spectral_references_precursor_mz'), 'spectral_references', ['precursor_mz'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('checksum', sa.String(length=32), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_sync_record_source_external_id')
    )
    op.create_index(op.f('ix_sync_records_external_id'), 'sync_records', ['external_id'], unique=False)
    op.create_index(op.f('ix_sync_records_job_id'), 'sync_records', ['job_id'], unique=False)
    op.create_index(op.f('ix_sync_records_source'), 'sync_records', ['source'], unique=False)
    op.create_index('ix_sync_records_source_external_id', 'sync_records', ['source', 'external_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_set_id', sa.UUID(), nullable=False),
    sa.Column('chromosome', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('ref_allele', sa.String(length=500), nullable=False),
    sa.Column('alt_allele', sa.String(length=500), nullable=False),
    sa.Column('rs_id', sa.String(length=50), nullable=True),
    sa.Column('hgvs_genomic', sa.String(length=500), nullable=True),
    sa.Column('hgvs_coding', sa.String(length=500), nullable=True),
    sa.Column('hgvs_protein', sa.String(length=500), nullable=True),
    sa.Column('gene_symbol', sa.String(length=100), nullable=True),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('consequence', sa.String(length=200), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('gnomad_af', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['variant_set_id'], ['variant_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_set_id', 'chromosome', 'position', 'ref_allele', 'alt_allele', name='uq_variant_set_locus')
    )
    op.create_index(op.f('ix_variants_chromosome'), 'variants', ['chromosome'], unique=False)
    op.create_index(op.f('ix_variants_consequence'), 'variants', ['consequence'], unique=False)
    op.create_index(op.f('ix_variants_feature_id'), 'variants', ['feature_id'], unique=False)
    op.create_index(op.f('ix_variants_gene_symbol'), 'variants', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_variants_hgvs_coding'), 'variants', ['hgvs_coding'], unique=False)
    op.create_index(op.f('ix_variants_hgvs_genomic'), 'variants', ['hgvs_genomic'], unique=False)
    op.create_index(op.f('ix_variants_hgvs_protein'), 'variants', ['hgvs_protein'], unique=False)
    op.create_index(op.f('ix_variants_impact'), 'variants', ['impact'], unique=False)
    op.create_index(op.f('ix_variants_position'), 'variants', ['position'], unique=False)
    op.create_index(op.f('ix_variants_rs_id'), 'variants', ['rs_id'], unique=False)
    op.create_index('ix_variants_set_gene', 'variants', ['variant_set_id', 'gene_symbol'], unique=False)
    op.create_index(op.f('ix_variants_variant_set_id'), 'variants', ['variant_set_id'], unique=False)
    op.create_table('binding_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('pocket_rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('center_x', sa.Float(), nullable=True),
    sa.Column('center_y', sa.Float(), nullable=True),
    sa.Column('center_z', sa.Float(), nullable=True),
    sa.Column('residues', sa.JSON(), nullable=True),
    sa.Column('pocket_pdb_path', sa.String(length=500), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['protein_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'detection_method', 'pocket_rank', name='uq_binding_site_rank')
    )
    op.create_index(op.f('ix_binding_sites_structure_id'), 'binding_sites', ['structure_id'], unique=False)
    op.create_table('factor_loadings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factor_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('loading', sa.Float(), nullable=False),
    sa.Column('abs_loading', sa.Float(), nullable=False),
    sa.Column('omics_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['latent_factors.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_id', 'feature_id', name='uq_factor_loading_factor_feature')
    )
    op.create_index(op.f('ix_factor_loadings_abs_loading'), 'factor_loadings', ['abs_loading'], unique=False)
    op.create_index('ix_factor_loadings_factor_abs', 'factor_loadings', ['factor_id', 'abs_loading'], unique=False)
    op.create_index(op.f('ix_factor_loadings_factor_id'), 'factor_loadings', ['factor_id'], unique=False)
    op.create_index(op.f('ix_factor_loadings_feature_id'), 'factor_loadings', ['feature_id'], unique=False)
    op.create_index(op.f('ix_factor_loadings_omics_type'), 'factor_loadings', ['omics_type'], unique=False)
    op.create_table('factor_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factor_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factor_id'], ['latent_factors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_id', 'sample_id', name='uq_factor_score_factor_sample')
    )
    op.create_index(op.f('ix_factor_scores_factor_id'), 'factor_scores', ['factor_id'], unique=False)
    op.create_index('ix_factor_scores_factor_sample', 'factor_scores', ['factor_id', 'sample_id'], unique=False)
    op.create_index(op.f('ix_factor_scores_sample_id'), 'factor_scores', ['sample_id'], unique=False)
    op.create_table('genomics_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organism', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organism', 'tool', 'version', name='uix_index_org_tool_ver')
    )
    op.create_table('lipid_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('spectral_reference_id', sa.UUID(), nullable=False),
    sa.Column('spectral_score', sa.Float(), nullable=False),
    sa.Column('mz_error_ppm', sa.Float(), nullable=True),
    sa.Column('matched_peaks', sa.Integer(), nullable=True),
    sa.Column('total_peaks', sa.Integer(), nullable=True),
    sa.Column('is_confident', sa.Boolean(), nullable=False),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('manually_reviewed', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['spectral_reference_id'], ['spectral_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lipid_annotations_feature_id'), 'lipid_annotations', ['feature_id'], unique=False)
    op.create_index('ix_lipid_annotations_feature_rank', 'lipid_annotations', ['feature_id', 'rank'], unique=False)
    op.create_index(op.f('ix_lipid_annotations_spectral_reference_id'), 'lipid_annotations', ['spectral_reference_id'], unique=False)
    op.create_table('nextflow_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sample_sheet_path', sa.String(length=500), nullable=True),
    sa.Column('genome', sa.String(length=50), nullable=True),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('work_dir', sa.String(length=500), nullable=True),
    sa.Column('nextflow_log', sa.String(length=500), nullable=True),
    sa.Column('multiqc_report', sa.String(length=500), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebook_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_path', sa.String(length=500), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_reviews_notebook_path'), 'notebook_reviews', ['notebook_path'], unique=False)
    op.create_index('ix_notebook_reviews_notebook_status', 'notebook_reviews', ['notebook_path', 'status'], unique=False)
    op.create_index(op.f('ix_notebook_reviews_status'), 'notebook_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_notebook_reviews_version_hash'), 'notebook_reviews', ['version_hash'], unique=False)
    op.create_table('structure_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['structure_id'], ['protein_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_files_structure_id'), 'structure_files', ['structure_id'], unique=False)
    op.create_table('sync_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('local_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['sync_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_conflicts_record_id'), 'sync_conflicts', ['record_id'], unique=False)
    op.create_index('ix_sync_conflicts_record_status', 'sync_conflicts', ['record_id', 'resolution_status'], unique=False)
    op.create_index(op.f('ix_sync_conflicts_resolution_status'), 'sync_conflicts', ['resolution_status'], unique=False)
    op.create_table('variant_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('annotation_source', sa.String(length=100), nullable=False),
    sa.Column('clinvar_id', sa.String(length=100), nullable=True),
    sa.Column('clinical_significance', sa.String(length=200), nullable=True),
    sa.Column('review_status', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=500), nullable=True),
    sa.Column('cadd_phred', sa.Float(), nullable=True),
    sa.Column('revel_score', sa.Float(), nullable=True),
    sa.Column('sift_prediction', sa.String(length=50), nullable=True),
    sa.Column('polyphen_prediction', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_annotations_annotation_source'), 'variant_annotations', ['annotation_source'], unique=False)
    op.create_index(op.f('ix_variant_annotations_clinical_significance'), 'variant_annotations', ['clinical_significance'], unique=False)
    op.create_index(op.f('ix_variant_annotations_clinvar_id'), 'variant_annotations', ['clinvar_id'], unique=False)
    op.create_index(op.f('ix_variant_annotations_variant_id'), 'variant_annotations', ['variant_id'], unique=False)
    op.create_index('ix_variant_annotations_variant_source', 'variant_annotations', ['variant_id', 'annotation_source'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_actor_id'), 'activity_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_event_type'), 'activity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_events_program_id'), 'activity_events', ['program_id'], unique=False)
    op.create_index(op.f('ix_activity_events_target_id'), 'activity_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_activity_events_target_type'), 'activity_events', ['target_type'], unique=False)
    op.create_table('batch_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('batch_map', sa.JSON(), nullable=True),
    sa.Column('corrected_dataset_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corrected_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connectivity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_signature_id', sa.UUID(), nullable=False),
    sa.Column('lincs_signature_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_type', sa.String(length=50), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lincs_signature_id'], ['lincs_signatures.id'], ),
    sa.ForeignKeyConstraint(['query_signature_id'], ['signatures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_signature_id', 'lincs_signature_id', 'score_type', name='uq_connectivity_score')
    )
    op.create_index(op.f('ix_connectivity_scores_lincs_signature_id'), 'connectivity_scores', ['lincs_signature_id'], unique=False)
    op.create_index('ix_connectivity_scores_query_score_type', 'connectivity_scores', ['query_signature_id', 'score_type'], unique=False)
    op.create_index(op.f('ix_connectivity_scores_query_signature_id'), 'connectivity_scores', ['query_signature_id'], unique=False)
    op.create_table('crispr_screens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('library_type', sa.String(length=100), nullable=True),
    sa.Column('cell_line', sa.String(length=200), nullable=True),
    sa.Column('treatment', sa.String(length=200), nullable=True),
    sa.Column('control_label', sa.String(length=200), nullable=True),
    sa.Column('treatment_label', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crispr_screens_cell_line'), 'crispr_screens', ['cell_line'], unique=False)
    op.create_index(op.f('ix_crispr_screens_dataset_id'), 'crispr_screens', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_crispr_screens_library_type'), 'crispr_screens', ['library_type'], unique=False)
    op.create_index(op.f('ix_crispr_screens_name'), 'crispr_screens', ['name'], unique=False)
    op.create_index(op.f('ix_crispr_screens_status'), 'crispr_screens', ['status'], unique=False)
    op.create_index(op.f('ix_crispr_screens_treatment'), 'crispr_screens', ['treatment'], unique=False)
    op.create_table('digest_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('notebook_path', sa.String(length=500), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_schedules_program_id'), 'digest_schedules', ['program_id'], unique=False)
    op.create_table('docking_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('binding_site_id', sa.UUID(), nullable=True),
    sa.Column('center_x', sa.Float(), nullable=True),
    sa.Column('center_y', sa.Float(), nullable=True),
    sa.Column('center_z', sa.Float(), nullable=True),
    sa.Column('size_x', sa.Float(), nullable=True),
    sa.Column('size_y', sa.Float(), nullable=True),
    sa.Column('size_z', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('compound_ids', sa.JSON(), nullable=True),
    sa.Column('exhaustiveness', sa.Integer(), nullable=False),
    sa.Column('total_compounds', sa.Integer(), nullable=True),
    sa.Column('completed_compounds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['binding_site_id'], ['binding_sites.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['protein_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docking_runs_binding_site_id'), 'docking_runs', ['binding_site_id'], unique=False)
    op.create_index(op.f('ix_docking_runs_structure_id'), 'docking_runs', ['structure_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('training_dataset_id', sa.UUID(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['training_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_ml_model_name_version')
    )
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tool', sa.String(length=20), nullable=False),
    sa.Column('input_fastq_path', sa.String(length=500), nullable=True),
    sa.Column('index_id', sa.UUID(), nullable=True),
    sa.Column('output_dir', sa.String(length=500), nullable=True),
    sa.Column('result_file', sa.String(length=500), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['genomics_indices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single_cell_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('h5ad_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('n_cells', sa.Integer(), nullable=True),
    sa.Column('n_genes', sa.Integer(), nullable=True),
    sa.Column('normalization_method', sa.String(length=100), nullable=True),
    sa.Column('hvg_count', sa.Integer(), nullable=True),
    sa.Column('clustering_method', sa.String(length=100), nullable=True),
    sa.Column('clustering_resolution', sa.Float(), nullable=True),
    sa.Column('has_pca', sa.Boolean(), nullable=False),
    sa.Column('has_umap', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_log', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_single_cell_datasets_dataset_id'), 'single_cell_datasets', ['dataset_id'], unique=False)
    op.create_table('cell_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('single_cell_dataset_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cell_type', sa.String(length=200), nullable=True),
    sa.Column('umap_1', sa.Float(), nullable=True),
    sa.Column('umap_2', sa.Float(), nullable=True),
    sa.Column('n_genes_detected', sa.Integer(), nullable=True),
    sa.Column('total_counts', sa.Float(), nullable=True),
    sa.Column('pct_mitochondrial', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['single_cell_dataset_id'], ['single_cell_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('single_cell_dataset_id', 'barcode', name='uq_cell_annotation_barcode')
    )
    op.create_index('ix_cell_annotations_dataset_cluster', 'cell_annotations', ['single_cell_dataset_id', 'cluster_id'], unique=False)
    op.create_index(op.f('ix_cell_annotations_single_cell_dataset_id'), 'cell_annotations', ['single_cell_dataset_id'], unique=False)
    op.create_table('cell_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('single_cell_dataset_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cell_type', sa.String(length=200), nullable=True),
    sa.Column('n_cells', sa.Integer(), nullable=True),
    sa.Column('marker_feature_ids', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['single_cell_dataset_id'], ['single_cell_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('single_cell_dataset_id', 'cluster_id', name='uq_cell_cluster')
    )
    op.create_index(op.f('ix_cell_clusters_single_cell_dataset_id'), 'cell_clusters', ['single_cell_dataset_id'], unique=False)
    op.create_table('cell_type_markers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('single_cell_dataset_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('gene_symbol', sa.String(length=50), nullable=True),
    sa.Column('log2_fold_change', sa.Float(), nullable=True),
    sa.Column('pval', sa.Float(), nullable=True),
    sa.Column('pval_adj', sa.Float(), nullable=True),
    sa.Column('pct_in_cluster', sa.Float(), nullable=True),
    sa.Column('pct_out_cluster', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['single_cell_dataset_id'], ['single_cell_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cell_type_markers_dataset_cluster', 'cell_type_markers', ['single_cell_dataset_id', 'cluster_id'], unique=False)
    op.create_index(op.f('ix_cell_type_markers_feature_id'), 'cell_type_markers', ['feature_id'], unique=False)
    op.create_index(op.f('ix_cell_type_markers_gene_symbol'), 'cell_type_markers', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_cell_type_markers_single_cell_dataset_id'), 'cell_type_markers', ['single_cell_dataset_id'], unique=False)
    op.create_table('crispr_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('guide_seq', sa.String(length=200), nullable=False),
    sa.Column('gene_symbol', sa.String(length=100), nullable=True),
    sa.Column('gene_id', sa.String(length=100), nullable=True),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['crispr_screens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'guide_seq', name='uq_crispr_guide_screen_seq')
    )
    op.create_index(op.f('ix_crispr_guides_feature_id'), 'crispr_guides', ['feature_id'], unique=False)
    op.create_index(op.f('ix_crispr_guides_gene_id'), 'crispr_guides', ['gene_id'], unique=False)
    op.create_index(op.f('ix_crispr_guides_gene_symbol'), 'crispr_guides', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_crispr_guides_guide_seq'), 'crispr_guides', ['guide_seq'], unique=False)
    op.create_index('ix_crispr_guides_screen_gene', 'crispr_guides', ['screen_id', 'gene_symbol'], unique=False)
    op.create_index(op.f('ix_crispr_guides_screen_id'), 'crispr_guides', ['screen_id'], unique=False)
    op.create_table('crispr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screen_id', sa.UUID(), nullable=False),
    sa.Column('gene_symbol', sa.String(length=100), nullable=True),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('beta_score', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('fdr', sa.Float(), nullable=True),
    sa.Column('neg_lfc', sa.Float(), nullable=True),
    sa.Column('pos_lfc', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_hit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['crispr_screens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crispr_results_feature_id'), 'crispr_results', ['feature_id'], unique=False)
    op.create_index(op.f('ix_crispr_results_gene_symbol'), 'crispr_results', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_crispr_results_is_hit'), 'crispr_results', ['is_hit'], unique=False)
    op.create_index(op.f('ix_crispr_results_rank'), 'crispr_results', ['rank'], unique=False)
    op.create_index('ix_crispr_results_screen_gene', 'crispr_results', ['screen_id', 'gene_symbol'], unique=False)
    op.create_index(op.f('ix_crispr_results_screen_id'), 'crispr_results', ['screen_id'], unique=False)
    op.create_table('docking_poses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('docking_run_id', sa.UUID(), nullable=False),
    sa.Column('compound_id', sa.UUID(), nullable=False),
    sa.Column('binding_affinity', sa.Float(), nullable=True),
    sa.Column('pose_rank', sa.Integer(), nullable=True),
    sa.Column('rmsd_lb', sa.Float(), nullable=True),
    sa.Column('rmsd_ub', sa.Float(), nullable=True),
    sa.Column('pose_pdbqt_path', sa.String(length=500), nullable=True),
    sa.Column('docked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.ForeignKeyConstraint(['docking_run_id'], ['docking_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docking_poses_compound_id'), 'docking_poses', ['compound_id'], unique=False)
    op.create_index(op.f('ix_docking_poses_docking_run_id'), 'docking_poses', ['docking_run_id'], unique=False)
    op.create_index('ix_docking_poses_run_rank', 'docking_poses', ['docking_run_id', 'pose_rank'], unique=False)
    op.create_table('model_monitoring_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('ground_truth', sa.Float(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('feature_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_monitoring_logs_created_at'), 'model_monitoring_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_input_hash'), 'model_monitoring_logs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_model_id'), 'model_monitoring_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_model_version'), 'model_monitoring_logs', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_monitoring_logs_prediction_id'), 'model_monitoring_logs', ['prediction_id'], unique=True)
    op.create_table('repository_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('activity_event_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_event_id'], ['activity_events.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['repository_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pose_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pose_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('ligand_atom', sa.String(length=200), nullable=True),
    sa.Column('protein_residue', sa.String(length=200), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pose_id'], ['docking_poses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pose_interactions_pose_id'), 'pose_interactions', ['pose_id'], unique=False)
    op.create_index('ix_pose_interactions_pose_type', 'pose_interactions', ['pose_id', 'interaction_type'], unique=False)
    op.create_table('pose_qualities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pose_id', sa.UUID(), nullable=False),
    sa.Column('num_hbonds', sa.Integer(), nullable=False),
    sa.Column('num_hydrophobic', sa.Integer(), nullable=False),
    sa.Column('num_salt_bridges', sa.Integer(), nullable=False),
    sa.Column('num_pi_stacking', sa.Integer(), nullable=False),
    sa.Column('num_pi_cation', sa.Integer(), nullable=False),
    sa.Column('num_halogen', sa.Integer(), nullable=False),
    sa.Column('num_metal', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('has_clashes', sa.Boolean(), nullable=False),
    sa.Column('ligand_efficiency', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pose_id'], ['docking_poses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pose_qualities_pose_id'), 'pose_qualities', ['pose_id'], unique=True)
    op.drop_index(op.f('ix_alerts_dataset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_subscription_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_activity_results_assay_id'), table_name='activity_results')
    op.drop_index(op.f('ix_activity_results_compound_id'), table_name='activity_results')
    op.drop_index(op.f('ix_adme_results_compound_id'), table_name='adme_results')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_constraint(op.f('uq_bookmarks_user_entity'), 'bookmarks', type_='unique')
    op.drop_index(op.f('ix_candidate_nominations_compound_id'), table_name='candidate_nominations')
    op.drop_index(op.f('ix_candidate_nominations_status'), table_name='candidate_nominations')
    op.drop_index(op.f('ix_candidate_nominations_tpp_id'), table_name='candidate_nominations')
    op.drop_index(op.f('ix_comments_entity'), table_name='comments')
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_type'), 'comments', ['entity_type'], unique=False)
    op.add_column('compounds', sa.Column('pubchem_cid', sa.Integer(), nullable=True))
    op.add_column('compounds', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('compounds', 'chembl_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_compounds_chembl_id'), 'compounds', ['chembl_id'], unique=False)
    op.create_index(op.f('ix_compounds_pubchem_cid'), 'compounds', ['pubchem_cid'], unique=False)
    op.drop_index(op.f('ix_discovered_studies_job_id'), table_name='discovered_studies')
    op.drop_index(op.f('ix_discovered_studies_status'), table_name='discovered_studies')
    op.drop_index(op.f('ix_feature_permissions_role'), table_name='feature_permissions')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_harvest_schedules_is_active'), table_name='harvest_schedules')
    op.drop_index(op.f('ix_literature_critiques_critique_type'), table_name='literature_critiques')
    op.drop_index(op.f('ix_literature_critiques_source_type'), table_name='literature_critiques')
    op.drop_index(op.f('ix_notes_entity'), table_name='notes')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_constraint(op.f('uq_ontology_terms_vocab_term'), 'ontology_terms', type_='unique')
    op.drop_index(op.f('ix_pk_studies_compound_id'), table_name='pk_studies')
    op.drop_index(op.f('ix_projects_team_id'), table_name='projects')
    op.add_column('rag_chunks', sa.Column('embedding', sa.Text(), nullable=True))
    op.add_column('rag_chunks', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('rag_chunks', sa.Column('extraction_job_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_rag_chunks_search_vector'), table_name='rag_chunks', postgresql_using='gin')
    op.create_index(op.f('ix_rag_chunks_extraction_job_id'), 'rag_chunks', ['extraction_job_id'], unique=False)
    op.create_foreign_key(None, 'rag_chunks', 'extraction_jobs', ['extraction_job_id'], ['id'])
    op.alter_column('report_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_schedules', 'last_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('report_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repository_subscriptions', 'last_checked',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('repository_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repository_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_repository_subscriptions_source'), table_name='repository_subscriptions')
    op.drop_index(op.f('ix_repository_subscriptions_user_id'), table_name='repository_subscriptions')
    op.create_index(op.f('ix_repository_subscriptions_repository_source'), 'repository_subscriptions', ['repository_source'], unique=False)
    op.drop_index(op.f('ix_samples_storage_location_id'), table_name='samples')
    op.drop_constraint(op.f('samples_barcode_key'), 'samples', type_='unique')
    op.drop_index(op.f('ix_saved_answers_question_id'), table_name='saved_answers')
    op.alter_column('saved_filters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_saved_filters_entity_type'), table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_user_id'), table_name='saved_filters')
    op.drop_index(op.f('ix_target_product_profiles_is_active'), table_name='target_product_profiles')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_toxicology_results_compound_id'), table_name='toxicology_results')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('company_role', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_workflow_executions_rule_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_rules_is_active'), table_name='workflow_rules')
    op.drop_index(op.f('ix_workflow_rules_trigger_type'), table_name='workflow_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workflow_rules_trigger_type'), 'workflow_rules', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_workflow_rules_is_active'), 'workflow_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_rule_id'), 'workflow_executions', ['rule_id'], unique=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_role')
    op.drop_column('users', 'company_id')
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_toxicology_results_compound_id'), 'toxicology_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_target_product_profiles_is_active'), 'target_product_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_saved_filters_user_id'), 'saved_filters', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_filters_entity_type'), 'saved_filters', ['entity_type'], unique=False)
    op.alter_column('saved_filters', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('ix_saved_answers_question_id'), 'saved_answers', ['question_id'], unique=False)
    op.create_unique_constraint(op.f('samples_barcode_key'), 'samples', ['barcode'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_samples_storage_location_id'), 'samples', ['storage_location_id'], unique=False)
    op.drop_index(op.f('ix_repository_subscriptions_repository_source'), table_name='repository_subscriptions')
    op.create_index(op.f('ix_repository_subscriptions_user_id'), 'repository_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_repository_subscriptions_source'), 'repository_subscriptions', ['repository_source'], unique=False)
    op.alter_column('repository_subscriptions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repository_subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repository_subscriptions', 'last_checked',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('report_schedules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_schedules', 'last_run_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('report_artifacts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'rag_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_rag_chunks_extraction_job_id'), table_name='rag_chunks')
    op.create_index(op.f('ix_rag_chunks_search_vector'), 'rag_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_column('rag_chunks', 'extraction_job_id')
    op.drop_column('rag_chunks', 'embedding_model')
    op.drop_column('rag_chunks', 'embedding')
    op.create_index(op.f('ix_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_index(op.f('ix_pk_studies_compound_id'), 'pk_studies', ['compound_id'], unique=False)
    op.create_unique_constraint(op.f('uq_ontology_terms_vocab_term'), 'ontology_terms', ['vocabulary', 'term'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notes_entity'), 'notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_literature_critiques_source_type'), 'literature_critiques', ['source_type'], unique=False)
    op.create_index(op.f('ix_literature_critiques_critique_type'), 'literature_critiques', ['critique_type'], unique=False)
    op.create_index(op.f('ix_harvest_schedules_is_active'), 'harvest_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feature_permissions_role'), 'feature_permissions', ['role'], unique=False)
    op.create_index(op.f('ix_discovered_studies_status'), 'discovered_studies', ['status'], unique=False)
    op.create_index(op.f('ix_discovered_studies_job_id'), 'discovered_studies', ['job_id'], unique=False)
    op.drop_index(op.f('ix_compounds_pubchem_cid'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_chembl_id'), table_name='compounds')
    op.alter_column('compounds', 'chembl_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('compounds', 'last_synced_at')
    op.drop_column('compounds', 'pubchem_cid')
    op.drop_index(op.f('ix_comments_entity_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.create_index(op.f('ix_comments_entity'), 'comments', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_candidate_nominations_tpp_id'), 'candidate_nominations', ['tpp_id'], unique=False)
    op.create_index(op.f('ix_candidate_nominations_status'), 'candidate_nominations', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_nominations_compound_id'), 'candidate_nominations', ['compound_id'], unique=False)
    op.create_unique_constraint(op.f('uq_bookmarks_user_entity'), 'bookmarks', ['user_id', 'entity_type', 'entity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_adme_results_compound_id'), 'adme_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_activity_results_compound_id'), 'activity_results', ['compound_id'], unique=False)
    op.create_index(op.f('ix_activity_results_assay_id'), 'activity_results', ['assay_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('alerts_dataset_id_fkey')),
    sa.ForeignKeyConstraint(['subscription_id'], ['repository_subscriptions.id'], name=op.f('alerts_subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_subscription_id'), 'alerts', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_alerts_dataset_id'), 'alerts', ['dataset_id'], unique=False)
    op.drop_index(op.f('ix_pose_qualities_pose_id'), table_name='pose_qualities')
    op.drop_table('pose_qualities')
    op.drop_index('ix_pose_interactions_pose_type', table_name='pose_interactions')
    op.drop_index(op.f('ix_pose_interactions_pose_id'), table_name='pose_interactions')
    op.drop_table('pose_interactions')
    op.drop_table('repository_notifications')
    op.drop_index(op.f('ix_model_monitoring_logs_prediction_id'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_model_version'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_model_id'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_input_hash'), table_name='model_monitoring_logs')
    op.drop_index(op.f('ix_model_monitoring_logs_created_at'), table_name='model_monitoring_logs')
    op.drop_table('model_monitoring_logs')
    op.drop_index('ix_docking_poses_run_rank', table_name='docking_poses')
    op.drop_index(op.f('ix_docking_poses_docking_run_id'), table_name='docking_poses')
    op.drop_index(op.f('ix_docking_poses_compound_id'), table_name='docking_poses')
    op.drop_table('docking_poses')
    op.drop_index(op.f('ix_crispr_results_screen_id'), table_name='crispr_results')
    op.drop_index('ix_crispr_results_screen_gene', table_name='crispr_results')
    op.drop_index(op.f('ix_crispr_results_rank'), table_name='crispr_results')
    op.drop_index(op.f('ix_crispr_results_is_hit'), table_name='crispr_results')
    op.drop_index(op.f('ix_crispr_results_gene_symbol'), table_name='crispr_results')
    op.drop_index(op.f('ix_crispr_results_feature_id'), table_name='crispr_results')
    op.drop_table('crispr_results')
    op.drop_index(op.f('ix_crispr_guides_screen_id'), table_name='crispr_guides')
    op.drop_index('ix_crispr_guides_screen_gene', table_name='crispr_guides')
    op.drop_index(op.f('ix_crispr_guides_guide_seq'), table_name='crispr_guides')
    op.drop_index(op.f('ix_crispr_guides_gene_symbol'), table_name='crispr_guides')
    op.drop_index(op.f('ix_crispr_guides_gene_id'), table_name='crispr_guides')
    op.drop_index(op.f('ix_crispr_guides_feature_id'), table_name='crispr_guides')
    op.drop_table('crispr_guides')
    op.drop_index(op.f('ix_cell_type_markers_single_cell_dataset_id'), table_name='cell_type_markers')
    op.drop_index(op.f('ix_cell_type_markers_gene_symbol'), table_name='cell_type_markers')
    op.drop_index(op.f('ix_cell_type_markers_feature_id'), table_name='cell_type_markers')
    op.drop_index('ix_cell_type_markers_dataset_cluster', table_name='cell_type_markers')
    op.drop_table('cell_type_markers')
    op.drop_index(op.f('ix_cell_clusters_single_cell_dataset_id'), table_name='cell_clusters')
    op.drop_table('cell_clusters')
    op.drop_index(op.f('ix_cell_annotations_single_cell_dataset_id'), table_name='cell_annotations')
    op.drop_index('ix_cell_annotations_dataset_cluster', table_name='cell_annotations')
    op.drop_table('cell_annotations')
    op.drop_index(op.f('ix_single_cell_datasets_dataset_id'), table_name='single_cell_datasets')
    op.drop_table('single_cell_datasets')
    op.drop_table('pipeline_jobs')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_docking_runs_structure_id'), table_name='docking_runs')
    op.drop_index(op.f('ix_docking_runs_binding_site_id'), table_name='docking_runs')
    op.drop_table('docking_runs')
    op.drop_index(op.f('ix_digest_schedules_program_id'), table_name='digest_schedules')
    op.drop_table('digest_schedules')
    op.drop_index(op.f('ix_crispr_screens_treatment'), table_name='crispr_screens')
    op.drop_index(op.f('ix_crispr_screens_status'), table_name='crispr_screens')
    op.drop_index(op.f('ix_crispr_screens_name'), table_name='crispr_screens')
    op.drop_index(op.f('ix_crispr_screens_library_type'), table_name='crispr_screens')
    op.drop_index(op.f('ix_crispr_screens_dataset_id'), table_name='crispr_screens')
    op.drop_index(op.f('ix_crispr_screens_cell_line'), table_name='crispr_screens')
    op.drop_table('crispr_screens')
    op.drop_index(op.f('ix_connectivity_scores_query_signature_id'), table_name='connectivity_scores')
    op.drop_index('ix_connectivity_scores_query_score_type', table_name='connectivity_scores')
    op.drop_index(op.f('ix_connectivity_scores_lincs_signature_id'), table_name='connectivity_scores')
    op.drop_table('connectivity_scores')
    op.drop_table('batch_corrections')
    op.drop_index(op.f('ix_activity_events_target_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_target_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_program_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_event_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_actor_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_variant_annotations_variant_source', table_name='variant_annotations')
    op.drop_index(op.f('ix_variant_annotations_variant_id'), table_name='variant_annotations')
    op.drop_index(op.f('ix_variant_annotations_clinvar_id'), table_name='variant_annotations')
    op.drop_index(op.f('ix_variant_annotations_clinical_significance'), table_name='variant_annotations')
    op.drop_index(op.f('ix_variant_annotations_annotation_source'), table_name='variant_annotations')
    op.drop_table('variant_annotations')
    op.drop_index(op.f('ix_sync_conflicts_resolution_status'), table_name='sync_conflicts')
    op.drop_index('ix_sync_conflicts_record_status', table_name='sync_conflicts')
    op.drop_index(op.f('ix_sync_conflicts_record_id'), table_name='sync_conflicts')
    op.drop_table('sync_conflicts')
    op.drop_index(op.f('ix_structure_files_structure_id'), table_name='structure_files')
    op.drop_table('structure_files')
    op.drop_index(op.f('ix_notebook_reviews_version_hash'), table_name='notebook_reviews')
    op.drop_index(op.f('ix_notebook_reviews_status'), table_name='notebook_reviews')
    op.drop_index('ix_notebook_reviews_notebook_status', table_name='notebook_reviews')
    op.drop_index(op.f('ix_notebook_reviews_notebook_path'), table_name='notebook_reviews')
    op.drop_table('notebook_reviews')
    op.drop_table('nextflow_jobs')
    op.drop_index(op.f('ix_lipid_annotations_spectral_reference_id'), table_name='lipid_annotations')
    op.drop_index('ix_lipid_annotations_feature_rank', table_name='lipid_annotations')
    op.drop_index(op.f('ix_lipid_annotations_feature_id'), table_name='lipid_annotations')
    op.drop_table('lipid_annotations')
    op.drop_table('genomics_indices')
    op.drop_index(op.f('ix_factor_scores_sample_id'), table_name='factor_scores')
    op.drop_index('ix_factor_scores_factor_sample', table_name='factor_scores')
    op.drop_index(op.f('ix_factor_scores_factor_id'), table_name='factor_scores')
    op.drop_table('factor_scores')
    op.drop_index(op.f('ix_factor_loadings_omics_type'), table_name='factor_loadings')
    op.drop_index(op.f('ix_factor_loadings_feature_id'), table_name='factor_loadings')
    op.drop_index(op.f('ix_factor_loadings_factor_id'), table_name='factor_loadings')
    op.drop_index('ix_factor_loadings_factor_abs', table_name='factor_loadings')
    op.drop_index(op.f('ix_factor_loadings_abs_loading'), table_name='factor_loadings')
    op.drop_table('factor_loadings')
    op.drop_index(op.f('ix_binding_sites_structure_id'), table_name='binding_sites')
    op.drop_table('binding_sites')
    op.drop_index(op.f('ix_variants_variant_set_id'), table_name='variants')
    op.drop_index('ix_variants_set_gene', table_name='variants')
    op.drop_index(op.f('ix_variants_rs_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_position'), table_name='variants')
    op.drop_index(op.f('ix_variants_impact'), table_name='variants')
    op.drop_index(op.f('ix_variants_hgvs_protein'), table_name='variants')
    op.drop_index(op.f('ix_variants_hgvs_genomic'), table_name='variants')
    op.drop_index(op.f('ix_variants_hgvs_coding'), table_name='variants')
    op.drop_index(op.f('ix_variants_gene_symbol'), table_name='variants')
    op.drop_index(op.f('ix_variants_feature_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_consequence'), table_name='variants')
    op.drop_index(op.f('ix_variants_chromosome'), table_name='variants')
    op.drop_table('variants')
    op.drop_index('ix_sync_records_source_external_id', table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_source'), table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_job_id'), table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_external_id'), table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index(op.f('ix_spectral_references_precursor_mz'), table_name='spectral_references')
    op.drop_index(op.f('ix_spectral_references_lipid_name'), table_name='spectral_references')
    op.drop_index(op.f('ix_spectral_references_lipid_class'), table_name='spectral_references')
    op.drop_index(op.f('ix_spectral_references_library_id'), table_name='spectral_references')
    op.drop_index(op.f('ix_spectral_references_inchi_key'), table_name='spectral_references')
    op.drop_index('ix_spectral_ref_library_precursor', table_name='spectral_references')
    op.drop_table('spectral_references')
    op.drop_index(op.f('ix_pubchem_bioassays_pubchem_cid'), table_name='pubchem_bioassays')
    op.drop_index(op.f('ix_pubchem_bioassays_compound_id'), table_name='pubchem_bioassays')
    op.drop_index('ix_pubchem_bioassays_cid_aid', table_name='pubchem_bioassays')
    op.drop_index(op.f('ix_pubchem_bioassays_aid'), table_name='pubchem_bioassays')
    op.drop_table('pubchem_bioassays')
    op.drop_index(op.f('ix_protein_structures_pdb_id'), table_name='protein_structures')
    op.drop_index(op.f('ix_protein_structures_feature_id'), table_name='protein_structures')
    op.drop_index(op.f('ix_protein_structures_alphafold_uniprot_id'), table_name='protein_structures')
    op.drop_table('protein_structures')
    op.drop_index(op.f('ix_lincs_genes_gene_symbol'), table_name='lincs_genes')
    op.drop_index(op.f('ix_lincs_genes_feature_id'), table_name='lincs_genes')
    op.drop_index(op.f('ix_lincs_genes_entrez_id'), table_name='lincs_genes')
    op.drop_table('lincs_genes')
    op.drop_index(op.f('ix_latent_factors_factor_index'), table_name='latent_factors')
    op.drop_index(op.f('ix_latent_factors_experiment_id'), table_name='latent_factors')
    op.drop_table('latent_factors')
    op.drop_index(op.f('ix_gene_burdens_variant_set_id'), table_name='gene_burdens')
    op.drop_index('ix_gene_burdens_set_gene', table_name='gene_burdens')
    op.drop_index(op.f('ix_gene_burdens_gene_symbol'), table_name='gene_burdens')
    op.drop_index(op.f('ix_gene_burdens_feature_id'), table_name='gene_burdens')
    op.drop_table('gene_burdens')
    op.drop_index(op.f('ix_extracted_documents_status'), table_name='extracted_documents')
    op.drop_index('ix_extracted_documents_job_status', table_name='extracted_documents')
    op.drop_index(op.f('ix_extracted_documents_job_id'), table_name='extracted_documents')
    op.drop_index('ix_extracted_documents_job_doc_type', table_name='extracted_documents')
    op.drop_index(op.f('ix_extracted_documents_doc_type'), table_name='extracted_documents')
    op.drop_table('extracted_documents')
    op.drop_index(op.f('ix_chembl_activities_target_chembl_id'), table_name='chembl_activities')
    op.drop_index('ix_chembl_activities_molecule_assay', table_name='chembl_activities')
    op.drop_index(op.f('ix_chembl_activities_compound_id'), table_name='chembl_activities')
    op.drop_index(op.f('ix_chembl_activities_chembl_molecule_id'), table_name='chembl_activities')
    op.drop_index(op.f('ix_chembl_activities_chembl_assay_id'), table_name='chembl_activities')
    op.drop_table('chembl_activities')
    op.drop_index(op.f('ix_variant_sets_status'), table_name='variant_sets')
    op.drop_index(op.f('ix_variant_sets_source_type'), table_name='variant_sets')
    op.drop_index(op.f('ix_variant_sets_name'), table_name='variant_sets')
    op.drop_table('variant_sets')
    op.drop_index(op.f('ix_sync_jobs_status'), table_name='sync_jobs')
    op.drop_index('ix_sync_jobs_source_status', table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_source'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_index(op.f('ix_spectral_libraries_version'), table_name='spectral_libraries')
    op.drop_index(op.f('ix_spectral_libraries_name'), table_name='spectral_libraries')
    op.drop_table('spectral_libraries')
    op.drop_index(op.f('ix_phenotype_gene_associations_hpo_id'), table_name='phenotype_gene_associations')
    op.drop_index(op.f('ix_phenotype_gene_associations_gene_symbol'), table_name='phenotype_gene_associations')
    op.drop_table('phenotype_gene_associations')
    op.drop_index(op.f('ix_multi_omics_experiments_status'), table_name='multi_omics_experiments')
    op.drop_index(op.f('ix_multi_omics_experiments_name'), table_name='multi_omics_experiments')
    op.drop_table('multi_omics_experiments')
    op.drop_index(op.f('ix_lincs_signatures_sig_id'), table_name='lincs_signatures')
    op.drop_index(op.f('ix_lincs_signatures_pert_iname'), table_name='lincs_signatures')
    op.drop_index(op.f('ix_lincs_signatures_pert_id'), table_name='lincs_signatures')
    op.drop_index(op.f('ix_lincs_signatures_cell_id'), table_name='lincs_signatures')
    op.drop_table('lincs_signatures')
    op.drop_index('ix_graph_edges_tgt_rel', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_entity_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_entity_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_src_rel', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_entity_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_entity_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_relationship_type'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_evidence_source'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_extraction_jobs_status', table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_batch_status', table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_batch_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_companies_subdomain'), table_name='companies')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

