"""add ip tracking tables

Revision ID: c08bd9a2f1a9
Revises: e32eb04dd92e
Create Date: 2025-12-29 17:31:43.856188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08bd9a2f1a9'
down_revision = 'e32eb04dd92e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

