"""add_variant_annotations_vep_fields

Revision ID: cacf74eae4ab
Revises: 772e7a60db92
Create Date: 2026-01-02 03:51:23.768151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cacf74eae4ab'
down_revision = '772e7a60db92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_annotations', sa.Column('consequence', sa.String(length=100), nullable=True))
    op.add_column('variant_annotations', sa.Column('impact', sa.String(length=20), nullable=True))
    op.add_column('variant_annotations', sa.Column('symbol', sa.String(length=50), nullable=True))
    op.add_column('variant_annotations', sa.Column('gene_id', sa.String(length=50), nullable=True))
    op.add_column('variant_annotations', sa.Column('transcript_id', sa.String(length=50), nullable=True))
    op.add_column('variant_annotations', sa.Column('biotype', sa.String(length=50), nullable=True))
    op.add_column('variant_annotations', sa.Column('amino_acids', sa.String(length=20), nullable=True))
    op.add_column('variant_annotations', sa.Column('codons', sa.String(length=20), nullable=True))
    op.add_column('variant_annotations', sa.Column('protein_position', sa.Integer(), nullable=True))
    op.add_column('variant_annotations', sa.Column('sift_score', sa.Float(), nullable=True))
    op.add_column('variant_annotations', sa.Column('polyphen_score', sa.Float(), nullable=True))
    op.add_column('variant_annotations', sa.Column('clin_sig', sa.String(length=100), nullable=True))
    op.add_column('variant_annotations', sa.Column('pubmed_ids', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('variant_annotations', sa.Column('source_version', sa.String(length=50), nullable=True))
    op.add_column('variant_annotations', sa.Column('annotated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_variant_annotations_consequence'), 'variant_annotations', ['consequence'], unique=False)
    op.create_index(op.f('ix_variant_annotations_impact'), 'variant_annotations', ['impact'], unique=False)
    op.create_index(op.f('ix_variant_annotations_symbol'), 'variant_annotations', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_annotations_symbol'), table_name='variant_annotations')
    op.drop_index(op.f('ix_variant_annotations_impact'), table_name='variant_annotations')
    op.drop_index(op.f('ix_variant_annotations_consequence'), table_name='variant_annotations')
    op.drop_column('variant_annotations', 'annotated_at')
    op.drop_column('variant_annotations', 'source_version')
    op.drop_column('variant_annotations', 'pubmed_ids')
    op.drop_column('variant_annotations', 'clin_sig')
    op.drop_column('variant_annotations', 'polyphen_score')
    op.drop_column('variant_annotations', 'sift_score')
    op.drop_column('variant_annotations', 'protein_position')
    op.drop_column('variant_annotations', 'codons')
    op.drop_column('variant_annotations', 'amino_acids')
    op.drop_column('variant_annotations', 'biotype')
    op.drop_column('variant_annotations', 'transcript_id')
    op.drop_column('variant_annotations', 'gene_id')
    op.drop_column('variant_annotations', 'symbol')
    op.drop_column('variant_annotations', 'impact')
    op.drop_column('variant_annotations', 'consequence')
    # ### end Alembic commands ###

