"""add electronic_signatures table

Revision ID: e32eb04dd92e
Revises: 63f6ba0e50e3
Create Date: 2025-12-29 16:26:42.117679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32eb04dd92e'
down_revision = '63f6ba0e50e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electronic_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('signature_hash', sa.String(length=128), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electronic_signatures_entity_id'), 'electronic_signatures', ['entity_id'], unique=False)
    op.create_index(op.f('ix_electronic_signatures_entity_type'), 'electronic_signatures', ['entity_type'], unique=False)
    op.create_index(op.f('ix_electronic_signatures_timestamp'), 'electronic_signatures', ['timestamp'], unique=False)
    op.create_index(op.f('ix_electronic_signatures_user_id'), 'electronic_signatures', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('old_checksum', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('new_checksum', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('changes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'new_checksum')
    op.drop_column('audit_logs', 'old_checksum')
    op.drop_index(op.f('ix_electronic_signatures_user_id'), table_name='electronic_signatures')
    op.drop_index(op.f('ix_electronic_signatures_timestamp'), table_name='electronic_signatures')
    op.drop_index(op.f('ix_electronic_signatures_entity_type'), table_name='electronic_signatures')
    op.drop_index(op.f('ix_electronic_signatures_entity_id'), table_name='electronic_signatures')
    op.drop_table('electronic_signatures')
    # ### end Alembic commands ###

