"""add mapping_refresh_logs table

Revision ID: ec9fe47e619d
Revises: 2cd9335a6a68
Create Date: 2025-12-31 14:08:10.432589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9fe47e619d'
down_revision = '2cd9335a6a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_refresh_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mapping_refresh_logs_source_status', 'mapping_refresh_logs', ['source', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mapping_refresh_logs_source_status', table_name='mapping_refresh_logs')
    op.drop_table('mapping_refresh_logs')
    # ### end Alembic commands ###

