"""Dashboard configuration and registry."""

from __future__ import annotations

import os

AUTH_DISABLED = os.environ.get("DISABLE_AUTH", "").lower() in ("1", "true", "yes")

DISCOVERY_PAGES = ["Overview", "Experiments", "Discovery Workflow", "Variant Tracking"]
ANALYSIS_PAGES = [
    "Analysis Tools",
    "Chemistry",
    "Visualizations",
    "Literature Analysis",
    "Candidate Selection",
    "HTS QC",
    "MOA Inference",
    "Cross-Omics Pathways",
    "Pipeline Runner",
    "Notebook Co-Pilot",
    "Notebook Generator",
]
ELN_PAGES = ["Protocols", "Sample Inventory", "Q&A Tracker"]
ADMIN_PAGES = [
    "Audit Logs",
    "Teams & Projects",
    "Feedback",
    "Import Data",
    "Workflows",
    "Feature Permissions",
    "Data Retention",
    "Ontology Management",
    "Report History",
    "Cytoscape Demo",
    "Entity Explorer",
    "Data Grid",
    "Genome Browser",
]

ALL_PAGES = [
    "Overview",
    "Getting Started",
    "Evaluation Wizard",
    "Chat",
    "Lab Notebook",
    "Sample Inventory",
    "Search",
    "Data Ingestion",
    "Repositories",
    "Discovery Workflow",
    "Variant Tracking",
    "Analysis Tools",
    "Visualizations",
    "Quality Checks",
    "Statistical Analysis",
    "Discovery",
    "Coverage Map",
    "Feature Recurrence",
    "Evidence Report",
    "Data Management",
    "System Health",
    "Audit Logs",
    "Relationships",
    "Datasets",
    "Programs",
    "Experiments",
    "Features",
    "Signatures",
    "Protocols",
    "Q&A Tracker",
    "Teams & Projects",
    "Feedback",
    "Literature",
    "Emails",
    "RAG Chunks",
    "Chemistry",
    "HTS QC",
    "MOA Inference",
    "RAG Query",
    "Cross-Omics",
    "Cross-Omics Pathways",
    "Import Data",
    "Compare",
    "Timeline",
    "Data Quality",
    "Generic Assays",
    "Workflows",
    "Literature Analysis",
    "Candidate Selection",
    "Email Settings",
    "Data Lineage",
    "Feature Permissions",
    "Schedule",
    "Cost Tracking",
    "Data Retention",
    "Ontology Management",
    "Report History",
    # Advanced visualization pages (admin tools)
    "Cytoscape Demo",
    "Entity Explorer",
    "Data Grid",
    "Genome Browser",
    "Notebook Co-Pilot",
    "Notebook Generator",
    "Pipeline Runner",
]

# Mapping page name -> (module_path, function_name)
PAGE_REGISTRY = {
    "Overview": ("scripts.dashboard.pages.overview", "render_overview_page"),
    "Getting Started": ("scripts.dashboard.pages.getting_started", "render_getting_started_page"),
    "Evaluation Wizard": ("scripts.dashboard.pages.evaluation_wizard", "render_evaluation_wizard"),
    "Chat": ("scripts.dashboard.pages.chat", "render_chat_page"),
    "Lab Notebook": ("scripts.dashboard.pages.lab_notebook", "render_lab_notebook_page"),
    "Sample Inventory": ("scripts.dashboard.pages.sample_inventory", "render_sample_inventory_page"),
    "Search": ("scripts.dashboard.pages.search", "render_search_page"),
    "Data Ingestion": ("scripts.dashboard.pages.ingestion", "render_ingestion_page"),
    "Repositories": ("scripts.dashboard.pages.repositories", "render_repositories_page"),
    "Discovery Workflow": ("scripts.dashboard.pages.discovery_workflow", "render_discovery_workflow_page"),
    "Variant Tracking": ("scripts.dashboard.pages.variants", "render_variants_page"),
    "Analysis Tools": ("scripts.dashboard.pages.analysis", "render_analysis_page"),
    "Visualizations": ("scripts.dashboard.pages.visualizations", "render_visualizations_page"),
    "Cytoscape Demo": ("scripts.dashboard.pages.visualizations.cytoscape_network", "render"),
    "Entity Explorer": ("scripts.dashboard.pages.visualizations.entity_explorer", "render"),
    "Data Grid": ("scripts.dashboard.pages.visualizations.data_grid", "render"),
    "Genome Browser": ("scripts.dashboard.pages.visualizations.genome_browser", "render"),
    "Quality Checks": ("scripts.dashboard.pages.quality_checks", "render_quality_checks_page"),
    "Statistical Analysis": ("scripts.dashboard.pages.statistical_analysis", "render_statistical_analysis_page"),
    "Discovery": ("scripts.dashboard.pages.discovery", "render_discovery_page"),
    "Coverage Map": ("scripts.dashboard.pages.coverage", "render_coverage_page"),
    "Feature Recurrence": ("scripts.dashboard.pages.feature_recurrence", "render_feature_recurrence_page"),
    "Evidence Report": ("scripts.dashboard.pages.evidence_report", "render_evidence_report_page"),
    "Data Management": ("scripts.dashboard.pages.management", "render_management_page"),
    "System Health": ("scripts.dashboard.pages.system_health", "render_system_health_page"),
    "Audit Logs": ("scripts.dashboard.pages.audit_logs", "render_audit_logs_page"),
    "Relationships": ("scripts.dashboard.pages.relationships", "render_relationships_page"),
    "Datasets": ("scripts.dashboard.pages.datasets", "render_datasets_page"),
    "Programs": ("scripts.dashboard.pages.programs", "render_programs_page"),
    "Experiments": ("scripts.dashboard.pages.experiments", "render_experiments_page"),
    "Protocols": ("scripts.dashboard.pages.protocols", "render_protocols_page"),
    "Q&A Tracker": ("scripts.dashboard.pages.qa_tracker", "render_qa_tracker_page"),
    "Teams & Projects": ("scripts.dashboard.pages.teams", "render_teams_page"),
    "Feedback": ("scripts.dashboard.pages.feedback", "render_feedback_page"),
    "Features": ("scripts.dashboard.pages.features", "render_features_page"),
    "Signatures": ("scripts.dashboard.pages.signatures", "render_signatures_page"),
    "Literature": ("scripts.dashboard.pages.literature", "render_literature_page"),
    "Emails": ("scripts.dashboard.pages.emails", "render_emails_page"),
    "RAG Chunks": ("scripts.dashboard.pages.rag_chunks", "render_rag_chunks_page"),
    "Chemistry": ("scripts.dashboard.pages.chemistry", "render_chemistry_page"),
    "HTS QC": ("scripts.dashboard.pages.hts_qc", "render_hts_qc_page"),
    "MOA Inference": ("scripts.dashboard.pages.moa_inference", "render_moa_inference_page"),
    "Cross-Omics Pathways": ("scripts.dashboard.pages.cross_omics_pathways", "render_cross_omics_pathways_page"),
    "RAG Query": ("scripts.dashboard.pages.rag_query", "render_rag_query_page"),
    "Generic Assays": ("scripts.dashboard.pages.generic_assays", "render_generic_assays_page"),
    "Cross-Omics": ("scripts.dashboard.pages.cross_omics", "render_cross_omics_page"),
    "Import Data": ("scripts.dashboard.pages.import_data", "render_import_page"),
    "Compare": ("scripts.dashboard.pages.compare", "render_compare_page"),
    "Timeline": ("scripts.dashboard.pages.timeline", "render_timeline_page"),
    "Data Quality": ("scripts.dashboard.pages.data_quality", "render_data_quality_page"),
    "Workflows": ("scripts.dashboard.pages.workflows", "render_workflows_page"),
    "Literature Analysis": ("scripts.dashboard.pages.literature_analysis", "render_literature_analysis_page"),
    "Candidate Selection": ("scripts.dashboard.pages.candidate_selection", "render_candidate_selection_page"),
    "Email Settings": ("scripts.dashboard.pages.email_settings", "render_email_settings_page"),
    "Data Lineage": ("scripts.dashboard.pages.data_lineage", "render_data_lineage_page"),
    "Feature Permissions": ("scripts.dashboard.pages.feature_permissions", "render_feature_permissions_page"),
    "Schedule": ("scripts.dashboard.pages.schedule", "render_schedule_page"),
    "Cost Tracking": ("scripts.dashboard.pages.cost_tracking", "render_cost_tracking_page"),
    "Data Retention": ("scripts.dashboard.pages.retention", "render_retention_page"),
    "Ontology Management": ("scripts.dashboard.pages.ontology", "render_ontology_page"),
    "Report History": ("scripts.dashboard.pages.report_history", "render_report_history_page"),
    "Notebook Co-Pilot": ("scripts.dashboard.pages.notebook_copilot", "render_notebook_copilot_page"),
    "Notebook Generator": ("scripts.dashboard.pages.notebook_generator", "render_notebook_generator_page"),
    "Pipeline Runner": ("scripts.dashboard.pages.pipeline_runner", "render_pipeline_runner_page"),
}

